const memory = [
  {
    id: "de-haben",
    term: "haben",
    translation: "tener",
    notes: "verbo auxiliar",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-mein",
    term: "mein",
    translation: "mi",
    notes: "pronombre posesivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-sein",
    term: "sein",
    translation: "ser/estar",
    notes: "verbo, también 'su' (posesivo)",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-war",
    term: "war",
    translation: "era/estaba",
    notes: "pasado de sein",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-ist",
    term: "ist",
    translation: "es/está",
    notes: "tercera persona singular de sein",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-ein",
    term: "ein",
    translation: "un/uno",
    notes: "artículo indefinido masculino/neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-nicht",
    term: "nicht",
    translation: "no",
    notes: "negación",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-so",
    term: "so",
    translation: "así/tan",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-bei",
    term: "bei",
    translation: "en/con/cerca de",
    notes: "preposición + dativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-in",
    term: "in",
    translation: "en",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-nur",
    term: "nur",
    translation: "solo/solamente",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-für",
    term: "für",
    translation: "para",
    notes: "preposición + acusativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-mit",
    term: "mit",
    translation: "con",
    notes: "preposición + dativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-und",
    term: "und",
    translation: "y",
    notes: "conjunción",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-oft",
    term: "oft",
    translation: "a menudo",
    notes: "adverbio de frecuencia",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-als",
    term: "als",
    translation: "que/cuando",
    notes: "conjunción comparativa/temporal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-aber",
    term: "aber",
    translation: "pero",
    notes: "conjunción adversativa",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-fahren",
    term: "fahren",
    translation: "conducir/viajar",
    notes: "verbo de movimiento",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-gerne",
    term: "gerne",
    translation: "con gusto",
    notes: "adverbio, expresa gusto",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-also",
    term: "also",
    translation: "entonces/así que",
    notes: "adverbio conectivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-aus",
    term: "aus",
    translation: "de/desde",
    notes: "preposición + dativo, origen",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-über",
    term: "über",
    translation: "sobre/acerca de",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-nach",
    term: "nach",
    translation: "después/hacia",
    notes: "preposición + dativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-links",
    term: "links",
    translation: "izquierda",
    notes: "adverbio de dirección",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-kommen",
    term: "kommen",
    translation: "venir",
    notes: "verbo de movimiento",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-groß",
    term: "groß",
    translation: "grande",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-gut",
    term: "gut",
    translation: "bueno",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-an",
    term: "an",
    translation: "en/junto a",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-zwei",
    term: "zwei",
    translation: "dos",
    notes: "número",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-auf",
    term: "auf",
    translation: "sobre/en",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-hören",
    term: "hören",
    translation: "oír/escuchar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-lang",
    term: "lang",
    translation: "largo",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-haar",
    term: "Haar",
    translation: "cabello/pelo",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-haare",
    term: "Haare",
    translation: "cabellos",
    notes: "plural de Haar",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-brille",
    term: "Brille",
    translation: "gafas",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-kopf",
    term: "Kopf",
    translation: "cabeza",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-größer",
    term: "größer",
    translation: "más grande",
    notes: "comparativo de groß",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-bin",
    term: "bin",
    translation: "soy/estoy",
    notes: "primera persona singular de sein",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-zurück",
    term: "zurück",
    translation: "atrás/de vuelta",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-gehen",
    term: "gehen",
    translation: "ir",
    notes: "verbo de movimiento",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-wie",
    term: "wie",
    translation: "cómo",
    notes: "adverbio interrogativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-um",
    term: "um",
    translation: "alrededor/a",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-nächste",
    term: "nächste",
    translation: "próximo/siguiente",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-greifen",
    term: "greifen",
    translation: "agarrar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-rechts",
    term: "rechts",
    translation: "derecha",
    notes: "adverbio de dirección",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-arm",
    term: "Arm",
    translation: "brazo",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-packen",
    term: "packen",
    translation: "agarrar/empacar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-zu",
    term: "zu",
    translation: "a/hacia",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-auge",
    term: "Auge",
    translation: "ojo",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-augen",
    term: "Augen",
    translation: "ojos",
    notes: "plural de Auge",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-auch",
    term: "auch",
    translation: "también",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-sagen",
    term: "sagen",
    translation: "decir",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-hoffentlich",
    term: "hoffentlich",
    translation: "ojalá/con suerte",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-ganz",
    term: "ganz",
    translation: "completamente/todo",
    notes: "adverbio/adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-ruhig",
    term: "ruhig",
    translation: "tranquilo/calmado",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-im",
    term: "im",
    translation: "en el",
    notes: "contracción de in + dem",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-film",
    term: "Film",
    translation: "película",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-vielleicht",
    term: "vielleicht",
    translation: "quizás/tal vez",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-wollen",
    term: "wollen",
    translation: "querer",
    notes: "verbo modal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-willst",
    term: "willst",
    translation: "quieres",
    notes: "segunda persona singular de wollen",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-versuchen",
    term: "versuchen",
    translation: "intentar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-immer",
    term: "immer",
    translation: "siempre",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-dann",
    term: "dann",
    translation: "entonces/luego",
    notes: "adverbio temporal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-auf-einmal",
    term: "auf einmal",
    translation: "de repente",
    notes: "expresión adverbial",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-hilfe",
    term: "Hilfe",
    translation: "ayuda",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-lassen",
    term: "lassen",
    translation: "dejar/permitir",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-loslasse",
    term: "loslasse",
    translation: "suelte",
    notes: "primera persona subjuntivo de loslassen",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-nie",
    term: "nie",
    translation: "nunca",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-selbst",
    term: "selbst",
    translation: "mismo/incluso",
    notes: "pronombre reflexivo/adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-damals",
    term: "damals",
    translation: "en aquel entonces",
    notes: "adverbio temporal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-sekunde",
    term: "Sekunde",
    translation: "segundo",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-drei",
    term: "drei",
    translation: "tres",
    notes: "número",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-können",
    term: "können",
    translation: "poder",
    notes: "verbo modal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-könnte",
    term: "könnte",
    translation: "podría",
    notes: "condicional de können",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-wieder",
    term: "wieder",
    translation: "otra vez/de nuevo",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-vorne",
    term: "vorne",
    translation: "adelante",
    notes: "adverbio de lugar",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-hand",
    term: "Hand",
    translation: "mano",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-händen",
    term: "Händen",
    translation: "manos",
    notes: "dativo plural de Hand",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-los",
    term: "los",
    translation: "vamos/adelante",
    notes: "interjección",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-erzählen",
    term: "erzählen",
    translation: "contar/narrar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-erzähl",
    term: "erzähl",
    translation: "cuenta",
    notes: "imperativo de erzählen",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-einen",
    term: "einen",
    translation: "un/uno",
    notes: "acusativo masculino de ein",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-großen",
    term: "großen",
    translation: "grande",
    notes: "forma declinada de groß",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-licht",
    term: "Licht",
    translation: "luz",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-sich",
    term: "sich",
    translation: "se",
    notes: "pronombre reflexivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-machen",
    term: "machen",
    translation: "hacer",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-denn",
    term: "denn",
    translation: "pues/porque",
    notes: "conjunción/partícula modal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-da",
    term: "da",
    translation: "ahí/allí",
    notes: "adverbio de lugar",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-strichmännchen",
    term: "Strichmännchen",
    translation: "muñeco de palitos",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-hitze",
    term: "Hitze",
    translation: "calor",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-speiseröhre",
    term: "Speiseröhre",
    translation: "esófago",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-eckig",
    term: "eckig",
    translation: "angular/cuadrado",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-abgehackt",
    term: "abgehackt",
    translation: "entrecortado/abrupto",
    notes: "adjetivo, participio de abhacken",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-schlägerei",
    term: "Schlägerei",
    translation: "pelea/riña",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-reh",
    term: "Reh",
    translation: "corzo",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-autoscheinwerfer",
    term: "Autoscheinwerfer",
    translation: "faro de coche",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-fett",
    term: "fett",
    translation: "gordo/grasoso",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-aufhören",
    term: "aufhören",
    translation: "parar/dejar de",
    notes: "verbo separable",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-faust",
    term: "Faust",
    translation: "puño",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-niere",
    term: "Niere",
    translation: "riñón",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-steuer",
    term: "Steuer",
    translation: "impuesto/volante",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-vorletzt",
    term: "vorletzt",
    translation: "penúltimo",
    notes: "adjetivo; uso: vorletzter Waggon",
    context: ["A1", "A2", "B2"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T11:45:36.206Z",
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-hart",
    term: "hart",
    translation: "duro",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-rücken",
    term: "Rücken",
    translation: "espalda",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-magen",
    term: "Magen",
    translation: "estómago",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-seltsam",
    term: "seltsam",
    translation: "extraño",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-leid",
    term: "Leid",
    translation: "sufrimiento",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-angst",
    term: "Angst",
    translation: "miedo/ansiedad",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-überfall",
    term: "Überfall",
    translation: "atraco/asalto",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-fair",
    term: "fair",
    translation: "justo",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-held",
    term: "Held",
    translation: "héroe",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
  },
  {
    id: "de-erst",
    term: "erst",
    translation: "primero/recién",
    notes: "adverbio temporal",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-klein",
    term: "klein",
    translation: "pequeño",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-eigentlich",
    term: "eigentlich",
    translation: "en realidad/realmente",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-holen",
    term: "holen",
    translation: "buscar/traer",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-meinen",
    term: "meinen",
    translation: "opinar/pensar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-bulle",
    term: "Bulle",
    translation: "policía (coloquial)",
    notes: "sustantivo masculino, también significa 'toro'",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-bullen",
    term: "Bullen",
    translation: "policías",
    notes: "plural de Bulle",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:33:11.176Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-kontrollieren",
    term: "kontrollieren",
    translation: "controlar/revisar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 7,
    lastPracticedAt: "2025-12-20T12:33:38.882Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-einfach",
    term: "einfach",
    translation: "simple/simplemente",
    notes: "adjetivo/adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 7,
    lastPracticedAt: "2025-12-20T12:33:44.934Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-faul",
    term: "faul",
    translation: "perezoso/flojo",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-sack",
    term: "Sack",
    translation: "saco",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 7,
    lastPracticedAt: "2025-12-20T12:33:49.068Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-bahnhof",
    term: "Bahnhof",
    translation: "estación de tren",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:34:07.164Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-kreuzung",
    term: "Kreuzung",
    translation: "cruce/intersección",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:34:15.551Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-straße",
    term: "Straße",
    translation: "calle",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-friedhof",
    term: "Friedhof",
    translation: "cementerio",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:34:35.570Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-etwa",
    term: "etwa",
    translation: "aproximadamente",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schätzen",
    term: "schätzen",
    translation: "estimar/valorar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 7,
    lastPracticedAt: "2025-12-20T12:34:51.944Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-oben",
    term: "oben",
    translation: "arriba",
    notes: "adverbio de lugar",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-typ",
    term: "Typ",
    translation: "tipo/tío",
    notes: "sustantivo masculino, coloquial para persona",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schwarz",
    term: "schwarz",
    translation: "negro",
    notes: "adjetivo/color",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schulter",
    term: "Schulter",
    translation: "hombro",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-komplett",
    term: "komplett",
    translation: "completo/completamente",
    notes: "adjetivo/adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-leder",
    term: "Leder",
    translation: "cuero",
    notes: "sustantivo neutro",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-unten",
    term: "unten",
    translation: "abajo",
    notes: "adverbio de lugar",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-gucken",
    term: "gucken",
    translation: "mirar",
    notes: "verbo, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-gleich",
    term: "gleich",
    translation: "igual/enseguida",
    notes: "adjetivo/adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-höhe",
    term: "Höhe",
    translation: "altura",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-flauschig",
    term: "flauschig",
    translation: "esponjoso/suave",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-stoff",
    term: "Stoff",
    translation: "tela/material",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: "2025-12-20T12:35:22.613Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-steigen",
    term: "steigen",
    translation: "subir/escalar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-gehirn",
    term: "Gehirn",
    translation: "cerebro",
    notes: "sustantivo neutro",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-welt",
    term: "Welt",
    translation: "mundo",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:36:55.586Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-neben",
    term: "neben",
    translation: "al lado de",
    notes: "preposición + dativo/acusativo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:37:00.680Z",
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-drehen",
    term: "drehen",
    translation: "girar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-laufen",
    term: "laufen",
    translation: "correr/caminar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-ampel",
    term: "Ampel",
    translation: "semáforo",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-oberarm",
    term: "Oberarm",
    translation: "parte superior del brazo",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-reißen",
    term: "reißen",
    translation: "arrancar/romper",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-herum",
    term: "herum",
    translation: "alrededor",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-dunkelgrün",
    term: "dunkelgrün",
    translation: "verde oscuro",
    notes: "adjetivo/color",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-wünschen",
    term: "wünschen",
    translation: "desear",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-laut",
    term: "laut",
    translation: "fuerte/ruidoso",
    notes: "adjetivo/adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-brüllen",
    term: "brüllen",
    translation: "gritar/rugir",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schwul",
    term: "schwul",
    translation: "gay",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-festhalten",
    term: "festhalten",
    translation: "sujetar/agarrar fuerte",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schreien",
    term: "schreien",
    translation: "gritar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-überrascht",
    term: "überrascht",
    translation: "sorprendido",
    notes: "adjetivo, participio de überraschen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-mann",
    term: "Mann",
    translation: "hombre",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-bein",
    term: "Bein",
    translation: "pierna",
    notes: "sustantivo neutro",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-beinen",
    term: "Beinen",
    translation: "piernas",
    notes: "dativo plural de Bein",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-judenwitz",
    term: "Judenwitz",
    translation: "chiste sobre judíos",
    notes: "sustantivo masculino, término sensible",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-zählen",
    term: "zählen",
    translation: "contar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-krallen",
    term: "krallen",
    translation: "agarrar con las uñas",
    notes: "verbo reflexivo: sich krallen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-ballen",
    term: "ballen",
    translation: "apretar/formar bola",
    notes: "verbo reflexivo: sich ballen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-hochsteigen",
    term: "hochsteigen",
    translation: "subir/ascender",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-flippen",
    term: "flippen",
    translation: "flipar/enloquecer",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-losrennen",
    term: "losrennen",
    translation: "echar a correr",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-überrumpeln",
    term: "überrumpeln",
    translation: "sorprender/abrumar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schütteln",
    term: "schütteln",
    translation: "sacudir/agitar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schiffbrüchiger",
    term: "Schiffbrüchiger",
    translation: "náufrago",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-treffen",
    term: "treffen",
    translation: "encontrar/acertar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-fallen",
    term: "fallen",
    translation: "caer",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-aufwachen",
    term: "aufwachen",
    translation: "despertarse",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-stecken",
    term: "stecken",
    translation: "meter/estar atascado",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-jedenfalls",
    term: "jedenfalls",
    translation: "en todo caso",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-handballen",
    term: "Handballen",
    translation: "palma de la mano",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-verwirrt",
    term: "verwirrt",
    translation: "confundido",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-krümmen",
    term: "krümmen",
    translation: "encorvarse/retorcerse",
    notes: "verbo reflexivo: sich krümmen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-wiegen",
    term: "wiegen",
    translation: "pesar/mecer",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-knacksen",
    term: "knacksen",
    translation: "crujir",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-walnuss",
    term: "Walnuss",
    translation: "nuez",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-rammen",
    term: "rammen",
    translation: "embestir/empotrar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-hallen",
    term: "hallen",
    translation: "resonar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-rutschen",
    term: "rutschen",
    translation: "resbalar/deslizar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-quetschen",
    term: "quetschen",
    translation: "aplastar/estrujar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-breitbeinig",
    term: "breitbeinig",
    translation: "con las piernas abiertas",
    notes: "adjetivo/adverbio",
    context: ["A2", "B2"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-bilden",
    term: "bilden",
    translation: "formar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schützend",
    term: "schützend",
    translation: "protector",
    notes: "adjetivo, participio de schützen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-rüstung",
    term: "Rüstung",
    translation: "armadura",
    notes: "sustantivo femenino",
    context: ["A2", "B2"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-ausholen",
    term: "ausholen",
    translation: "echarse atrás para golpear",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-ansehen",
    term: "ansehen",
    translation: "mirar/parecer",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-angucken",
    term: "angucken",
    translation: "mirar",
    notes: "verbo separable, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-fressen",
    term: "fressen",
    translation: "comer (animales)/devorar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-schließlich",
    term: "schließlich",
    translation: "finalmente",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-mitfahren",
    term: "mitfahren",
    translation: "ir con/acompañar",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-tippen",
    term: "tippen",
    translation: "teclear/tocar ligeramente",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-aussage",
    term: "Aussage",
    translation: "declaración",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-anzeigen",
    term: "anzeigen",
    translation: "denunciar/mostrar",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-rechtsschutzversicherung",
    term: "Rechtsschutzversicherung",
    translation: "seguro de defensa jurídica",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-gericht",
    term: "Gericht",
    translation: "tribunal/plato",
    notes: "sustantivo neutro",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-wehren",
    term: "wehren",
    translation: "defenderse",
    notes: "verbo reflexivo: sich wehren",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-katzensatt",
    term: "katzensatt",
    translation: "llenísimo",
    notes: "adjetivo, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-verdreschen",
    term: "verdreschen",
    translation: "apalear",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-retten",
    term: "retten",
    translation: "rescatar/salvar",
    notes: "verbo; participio: gerettet",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-weglaufen",
    term: "weglaufen",
    translation: "huir/irse corriendo",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-einzelheit",
    term: "Einzelheit",
    translation: "detalle",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-vergebung",
    term: "Vergebung",
    translation: "perdón",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-priester",
    term: "Priester",
    translation: "sacerdote",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-tacken",
    term: "Tacken",
    translation: "tachuela/clavo pequeño",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-klären",
    term: "klären",
    translation: "aclarar/resolver",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-scheiß",
    term: "Scheiß",
    translation: "mierda",
    notes: "sustantivo masculino, vulgar",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-feigling",
    term: "Feigling",
    translation: "cobarde",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-die-klappe-halten",
    term: "die Klappe halten",
    translation: "callarse/cerrar la boca",
    notes: "expresión verbal, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-tausch",
    term: "Tausch",
    translation: "intercambio",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-eine-reinziehen",
    term: "eine reinziehen",
    translation: "dar un golpe",
    notes: "expresión verbal, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
  },
  {
    id: "de-verfilzt",
    term: "verfilzt",
    translation: "enmarañado/afieltrado",
    notes: "adjetivo, participio de verfilzen",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-bunt",
    term: "bunt",
    translation: "colorido",
    notes: "adjetivo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T11:45:48.780Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-häkeln",
    term: "häkeln",
    translation: "hacer ganchillo",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pflanzen",
    term: "pflanzen",
    translation: "plantar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T11:46:05.524Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sich-ducken",
    term: "sich ducken",
    translation: "agacharse",
    notes: "verbo reflexivo: sich ducken",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-bescheuert",
    term: "bescheuert",
    translation: "estúpido",
    notes: "adjetivo, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: "2025-12-20T11:46:47.020Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poltern",
    term: "poltern",
    translation: "retumbar/armar ruido",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-erwischen",
    term: "erwischen",
    translation: "atrapar/pillar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-riesenreifen",
    term: "Riesenreifen",
    translation: "neumático gigante",
    notes: "sustantivo masculino",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-fuchteln",
    term: "fuchteln",
    translation: "agitar los brazos",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sprinten",
    term: "sprinten",
    translation: "esprintar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sich-quetschen",
    term: "sich quetschen",
    translation: "apretujarse",
    notes: "verbo reflexivo: sich quetschen",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-zuschnappen",
    term: "zuschnappen",
    translation: "cerrarse de golpe/morder",
    notes: "verbo separable",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-aufreißen",
    term: "aufreißen",
    translation: "rasgar/abrir de golpe",
    notes: "verbo separable",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-seinesgleichen",
    term: "seinesgleichen",
    translation: "de su calaña/iguales",
    notes: "pronombre/sustantivo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-tänzeln",
    term: "tänzeln",
    translation: "danzar/andar dando saltitos",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-zimmern",
    term: "zimmern",
    translation: "carpintear/armar",
    notes: "verbo, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sacken",
    term: "sacken",
    translation: "hundirse/asentarse",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-drankommen",
    term: "drankommen",
    translation: "tocar el turno/llegar",
    notes: "verbo, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-riskant",
    term: "riskant",
    translation: "arriesgado",
    notes: "adjetivo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-hampelmann",
    term: "Hampelmann",
    translation: "muñeco articulado",
    notes: "sustantivo masculino",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-kopfhaut",
    term: "Kopfhaut",
    translation: "cuero cabelludo",
    notes: "sustantivo femenino",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-abziehen",
    term: "abziehen",
    translation: "quitar/arrancar",
    notes: "verbo separable",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-taumeln",
    term: "taumeln",
    translation: "tambalearse",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-riesengewese",
    term: "Riesengewese",
    translation: "gran alboroto",
    notes: "sustantivo neutro, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-verfrachten",
    term: "verfrachten",
    translation: "transportar/cargar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-lauern",
    term: "lauern",
    translation: "acechar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-hinkriegen",
    term: "hinkriegen",
    translation: "conseguir/arreglar",
    notes: "verbo, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-habe",
    term: "habe",
    translation: "tengo",
    notes: "verbo, 1ra persona de haben",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:51.203Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-ersten",
    term: "ersten",
    translation: "primer/primero",
    notes: "adjetivo ordinal",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:26:24.360Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-nazi",
    term: "Nazi",
    translation: "nazi",
    notes: "sustantivo",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-erwischt",
    term: "erwischt",
    translation: "atrapado",
    notes: "participio de erwischen",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T12:31:45.896Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-kleiner",
    term: "kleiner",
    translation: "más pequeño",
    notes: "comparativo",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:26:21.080Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-wessi",
    term: "Wessi",
    translation: "alemán occidental",
    notes: "sustantivo, coloquial",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:32:33.715Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-kaventsmann",
    term: "Kaventsmann",
    translation: "gigante/monstruo",
    notes: "sustantivo, coloquial",
    context: ["B2", "sustantivo"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:32:45.594Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-brandenburg",
    term: "Brandenburg",
    translation: "Brandeburgo",
    notes: "nombre propio (estado)",
    context: ["A2", "nombre propio"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:29:24.089Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-rumlaufen",
    term: "rumlaufen",
    translation: "andar por ahí",
    notes: "verbo separable",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 8,
    lastPracticedAt: "2025-12-20T12:31:18.825Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-dabei",
    term: "Dabei",
    translation: "mientras/también",
    notes: "adverbio",
    context: ["A2", "adverbio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-wollte",
    term: "wollte",
    translation: "quería",
    notes: "verbo modal (querer)",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:48.829Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-dope",
    term: "Dope",
    translation: "droga",
    notes: "sustantivo, coloquial",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-marik",
    term: "Marik",
    translation: "Marik",
    notes: "nombre propio",
    context: ["A1", "nombre propio"],
    contextForPractice: [],
    baseScore: 12,
    lastPracticedAt: "2025-12-20T12:17:42.551Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-macht",
    term: "macht",
    translation: "hace",
    notes: "verbo, 3ra persona de machen",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:41.173Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-zivi",
    term: "Zivi",
    translation: "objetor de servicio civil",
    notes: "sustantivo, coloquial",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:32:53.195Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-meint",
    term: "meint",
    translation: "piensa/opina",
    notes: "verbo, 3ra persona de meinen",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:45.856Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-fauler",
    term: "fauler",
    translation: "más perezoso",
    notes: "comparativo",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 3,
    lastPracticedAt: "2025-12-20T12:33:54.576Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-fahre",
    term: "fahre",
    translation: "conduzco/viajo",
    notes: "verbo, 1ra persona de fahren",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:45.325Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-s-bahn",
    term: "S-Bahn",
    translation: "tren urbano",
    notes: "sustantivo",
    context: ["A2", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:30:38.047Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-bahn",
    term: "Bahn",
    translation: "tren/ferrocarril",
    notes: "sustantivo",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:40.064Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-berlin",
    term: "Berlin",
    translation: "Berlín",
    notes: "nombre propio",
    context: ["A1", "nombre propio"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:17:54.184Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-soll",
    term: "soll",
    translation: "debe/se supone",
    notes: "verbo modal (sollen)",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:44.935Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-laufe",
    term: "laufe",
    translation: "corro/ando",
    notes: "verbo, 1ra persona de laufen",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:44.763Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-dem",
    term: "dem",
    translation: "al/el",
    notes: "artículo dativo",
    context: ["A1", "artículo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:24:50.778Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-raus",
    term: "raus",
    translation: "fuera",
    notes: "adverbio",
    context: ["A1", "adverbio"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:25:56.492Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-einem",
    term: "einem",
    translation: "a un/uno",
    notes: "artículo indefinido dativo",
    context: ["A1", "artículo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:44:00.840Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-lauter",
    term: "lauter",
    translation: "muchos/muchas",
    notes: "determinante",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-einfamilienhäusern",
    term: "Einfamilienhäusern",
    translation: "casas unifamiliares",
    notes: "sustantivo plural (dativo)",
    context: ["B2", "sustantivo"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: "2025-12-20T12:33:27.266Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-kommt",
    term: "kommt",
    translation: "viene",
    notes: "verbo, 3ra persona de kommen",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:44.320Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-glatze",
    term: "Glatze",
    translation: "calva",
    notes: "sustantivo",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 3,
    lastPracticedAt: "2025-12-20T12:34:42.501Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-entgegen",
    term: "entgegen",
    translation: "en dirección a",
    notes: "preposición/adverbio",
    context: ["B1", "preposición"],
    contextForPractice: [],
    baseScore: 2,
    lastPracticedAt: "2025-12-20T12:34:45.316Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-eins",
    term: "eins",
    translation: "uno",
    notes: "numeral",
    context: ["A1", "numeral"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:24:29.221Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-siebzig",
    term: "siebzig",
    translation: "setenta",
    notes: "numeral",
    context: ["A1", "numeral"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:24:27.441Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-obenrum",
    term: "Obenrum",
    translation: "parte superior",
    notes: "adverbio, coloquial",
    context: ["B1", "adverbio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sieht",
    term: "sieht",
    translation: "ve",
    notes: "verbo, 3ra persona de sehen",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:44.174Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-bullig",
    term: "bullig",
    translation: "robusto",
    notes: "adjetivo",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-wegen",
    term: "wegen",
    translation: "por/a causa de",
    notes: "preposición",
    context: ["A2", "preposición"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: "2025-12-20T12:29:32.250Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-donkey",
    term: "Donkey",
    translation: "burro",
    notes: "sustantivo, anglicismo/marca",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-jacke",
    term: "Jacke",
    translation: "chaqueta",
    notes: "sustantivo",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:33.969Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-den",
    term: "den",
    translation: "el/los",
    notes: "artículo acusativo",
    context: ["A1", "artículo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:24:46.564Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-schultern",
    term: "Schultern",
    translation: "hombros",
    notes: "sustantivo plural",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: "2025-12-20T12:23:37.254Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-spillerbeinchen",
    term: "Spillerbeinchen",
    translation: "piernitas (insulto)",
    notes: "sustantivo, coloquial",
    context: ["B2", "sustantivo"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: "2025-12-20T12:35:41.309Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-gleicher",
    term: "gleicher",
    translation: "igual",
    notes: "adjetivo",
    context: ["A2", "adjetivo"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: "2025-12-20T12:35:49.922Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sind",
    term: "sind",
    translation: "son",
    notes: "verbo, 3ra persona plural de sein",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:44.054Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-hore",
    term: "höre",
    translation: "oigo/escucho",
    notes: "verbo, 1ra persona de hören",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:43.934Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-schwuchtel",
    term: "Schwuchtel",
    translation: "maricón",
    notes: "sustantivo, insulto homofóbico",
    context: ["B2", "sustantivo"],
    contextForPractice: [],
    baseScore: 9,
    lastPracticedAt: "2025-12-20T12:35:57.069Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-hippie",
    term: "Hippie",
    translation: "hippie",
    notes: "sustantivo",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sensor",
    term: "Sensor",
    translation: "sensor",
    notes: "sustantivo",
    context: ["A2", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:30:40.580Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-angesprungen",
    term: "angesprungen",
    translation: "saltó sobre/encendido",
    notes: "participio de anspringen",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-meine",
    term: "meine",
    translation: "mi/mis",
    notes: "posesivo",
    context: ["A1", "pronombre"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:45:03.394Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-langen",
    term: "langen",
    translation: "largos",
    notes: "adjetivo",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:26:15.854Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-flauschige",
    term: "flauschige",
    translation: "suaves/afelpadas",
    notes: "adjetivo",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-kopfe",
    term: "Köpfe",
    translation: "cabezas",
    notes: "sustantivo plural",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:16.858Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-dieses",
    term: "dieses",
    translation: "este/esto",
    notes: "demostrativo",
    context: ["A1", "pronombre"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:59.986Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-ballt",
    term: "ballt",
    translation: "aprieta",
    notes: "verbo, 3ra persona de ballen",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-meinem",
    term: "meinem",
    translation: "a mi",
    notes: "posesivo (dativo)",
    context: ["A2", "pronombre"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:30:06.188Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-zusammen",
    term: "zusammen",
    translation: "juntos",
    notes: "adverbio",
    context: ["A1", "adverbio"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:25:53.824Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-steigt",
    term: "steigt",
    translation: "sube",
    notes: "verbo, 3ra persona de steigen",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 3,
    lastPracticedAt: "2025-12-20T12:30:58.025Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-hoch",
    term: "hoch",
    translation: "alto/arriba",
    notes: "adverbio/adjetivo",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:26:13.359Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-flippt",
    term: "flippt",
    translation: "se descontrola",
    notes: "verbo, coloquial",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-dieser",
    term: "dieser",
    translation: "este",
    notes: "demostrativo",
    context: ["A1", "pronombre"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:58.278Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-gehe",
    term: "gehe",
    translation: "voy",
    notes: "verbo, 1ra persona de gehen",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:43.761Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-roboter",
    term: "Roboter",
    translation: "robot",
    notes: "sustantivo",
    context: ["A2", "sustantivo"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:30:34.608Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-eckige",
    term: "eckige",
    translation: "angulares",
    notes: "adjetivo",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-abgehackte",
    term: "abgehackte",
    translation: "entrecortados",
    notes: "adjetivo",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-schritte",
    term: "Schritte",
    translation: "pasos",
    notes: "sustantivo plural",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:14.113Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-drehe",
    term: "drehe",
    translation: "giro",
    notes: "verbo, 1ra persona de drehen",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T12:31:47.748Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-typen",
    term: "Typen",
    translation: "tipos",
    notes: "sustantivo plural, coloquial",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-nachsten",
    term: "nächsten",
    translation: "siguiente",
    notes: "adjetivo",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:26:11.079Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-greife",
    term: "greife",
    translation: "agarro",
    notes: "verbo, 1ra persona de greifen",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T12:31:43.760Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-seinen",
    term: "seinen",
    translation: "su",
    notes: "posesivo (masc./acc.)",
    context: ["A1", "pronombre"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:55.997Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-rechten",
    term: "rechten",
    translation: "derecho",
    notes: "adjetivo",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:26:07.906Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-packe",
    term: "packe",
    translation: "agarro",
    notes: "verbo, 1ra persona de packen",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 2,
    lastPracticedAt: "2025-12-20T12:31:36.292Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-reisse",
    term: "reiße",
    translation: "arranco",
    notes: "verbo, 1ra persona de reißen",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:31:22.745Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-ey",
    term: "Ey",
    translation: "ey",
    notes: "interjección, coloquial",
    context: ["A2", "interjección"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:29:18.441Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-seine",
    term: "Seine",
    translation: "su",
    notes: "posesivo",
    context: ["A1", "pronombre"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:53.877Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-wunsch",
    term: "wünschte",
    translation: "deseaba",
    notes: "verbo (wünschen)",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:30:48.625Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-waren",
    term: "wären",
    translation: "serían/fueran",
    notes: "verbo, Konjunktiv de sein",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-hallo",
    term: "Hallo",
    translation: "hola",
    notes: "saludo",
    context: ["A1", "interjección"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:17:28.300Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sage",
    term: "sage",
    translation: "digo",
    notes: "verbo, 1ra persona de sagen",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:43.603Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-lachle",
    term: "lächle",
    translation: "sonrío",
    notes: "verbo, 1ra persona de lächeln",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T12:31:38.510Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sogar",
    term: "sogar",
    translation: "incluso",
    notes: "adverbio",
    context: ["A2", "adverbio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-versucht",
    term: "versucht",
    translation: "intenta/intentó",
    notes: "verbo (versuchen)",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:30:51.101Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-loszureißen",
    term: "loszureißen",
    translation: "arrancar",
    notes: "verbo separable",
    context: ["B2", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-wird",
    term: "wird",
    translation: "será/se vuelve",
    notes: "verbo, 3ra persona de werden",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:43.241Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-brullt",
    term: "brüllt",
    translation: "grita/ruge",
    notes: "verbo",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-ware",
    term: "wäre",
    translation: "sería",
    notes: "verbo, Konjunktiv de sein",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-schwules",
    term: "schwules",
    translation: "gay",
    notes: "adjetivo",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-arschloch",
    term: "Arschloch",
    translation: "imbécil/cabrón",
    notes: "sustantivo, insulto",
    context: ["B2", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-halte",
    term: "halte",
    translation: "sostengo",
    notes: "verbo, 1ra persona de halten",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T12:31:40.242Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-fest",
    term: "fest",
    translation: "firme",
    notes: "adjetivo/adverbio",
    context: ["A2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-schreit",
    term: "schreit",
    translation: "grita",
    notes: "verbo",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 3,
    lastPracticedAt: "2025-12-20T12:31:14.073Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-einmal",
    term: "einmal",
    translation: "una vez",
    notes: "adverbio",
    context: ["A1", "adverbio"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:25:51.907Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-dass",
    term: "dass",
    translation: "que",
    notes: "conjunción",
    context: ["A2", "conjunción"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:29:12.567Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-parkplatz",
    term: "Parkplatz",
    translation: "estacionamiento",
    notes: "sustantivo",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:10.458Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-torsten",
    term: "Torsten",
    translation: "Torsten",
    notes: "nombre propio",
    context: ["A1", "nombre propio"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:17:42.419Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-zermanscht",
    term: "zermanscht",
    translation: "aplastado",
    notes: "participio de zermanschen",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-tomate",
    term: "Tomate",
    translation: "tomate",
    notes: "sustantivo",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:06.592Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-sekunden",
    term: "Sekunden",
    translation: "segundos",
    notes: "sustantivo plural",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:23:03.244Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-glatzenmann",
    term: "Glatzenmann",
    translation: "hombre calvo",
    notes: "sustantivo",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-dunnen",
    term: "dünnen",
    translation: "delgados",
    notes: "adjetivo",
    context: ["A2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-uberrumpelt",
    term: "überrumpelt",
    translation: "sorprendido",
    notes: "participio de überrumpeln",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-beiden",
    term: "beiden",
    translation: "ambos",
    notes: "pronombre",
    context: ["A2", "pronombre"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:29:57.016Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-arier",
    term: "Arier",
    translation: "ario",
    notes: "sustantivo",
    context: ["B2", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-schuttle",
    term: "schüttle",
    translation: "sacudo",
    notes: "verbo, 1ra persona de schütteln",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T12:31:05.624Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-palme",
    term: "Palme",
    translation: "palma",
    notes: "sustantivo",
    context: ["A2", "sustantivo"],
    contextForPractice: [],
    baseScore: 6,
    lastPracticedAt: "2025-12-20T12:30:32.794Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-guckt",
    term: "guckt",
    translation: "mira",
    notes: "verbo, coloquial",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 1,
    lastPracticedAt: "2025-12-20T12:31:42.134Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-grunen",
    term: "grünen",
    translation: "verdes",
    notes: "adjetivo",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:26:05.145Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-autoscheinwerfers",
    term: "Autoscheinwerfers",
    translation: "del faro del coche",
    notes: "sustantivo (genitivo)",
    context: ["B2", "sustantivo"],
    contextForPractice: [],
    baseScore: 2,
    lastPracticedAt: "2025-12-20T12:46:46.973Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-zahle",
    term: "zähle",
    translation: "cuento",
    notes: "verbo, 1ra persona de zählen",
    context: ["A1", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:22:42.686Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-krallt",
    term: "krallt",
    translation: "agarra con fuerza",
    notes: "verbo",
    context: ["B1", "verbo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-hey",
    term: "Hey",
    translation: "hey",
    notes: "interjección",
    context: ["A1", "interjección"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:46:19.409Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-solls",
    term: "soll's",
    translation: "debe/se supone",
    notes: "contracción de 'soll es'",
    context: ["A2", "verbo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:31:02.569Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-donkey-jacke",
    term: "Donkey-Jacke",
    translation: "chaqueta Donkey",
    notes: "sustantivo compuesto",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-hippie-sensor",
    term: "Hippie-Sensor",
    translation: "sensor hippie",
    notes: "sustantivo compuesto",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-20T12:36:05.297Z",
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-inka-jacke",
    term: "Inka-Jacke",
    translation: "chaqueta Inka",
    notes: "sustantivo compuesto",
    context: ["B1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-deutsche",
    term: "Deutsche",
    translation: "alemanes/alemanas",
    notes: "sustantivo plural",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pronomen",
    term: "Pronomen",
    translation: "pronombre",
    notes: "termino gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-personalpronomen",
    term: "Personalpronomen",
    translation: "pronombre personal",
    notes: "termino gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-nominativ",
    term: "Nominativ",
    translation: "nominativo",
    notes: "caso gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-akkusativ",
    term: "Akkusativ",
    translation: "acusativo",
    notes: "caso gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-dativ",
    term: "Dativ",
    translation: "dativo",
    notes: "caso gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-genitiv",
    term: "Genitiv",
    translation: "genitivo",
    notes: "caso gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-possessivpronomen",
    term: "Possessivpronomen",
    translation: "pronombre posesivo",
    notes: "termino gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-reflexivpronomen",
    term: "Reflexivpronomen",
    translation: "pronombre reflexivo",
    notes: "termino gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demonstrativpronomen",
    term: "Demonstrativpronomen",
    translation: "pronombres demostrativos",
    notes: "termino gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-relativpronomen",
    term: "Relativpronomen",
    translation: "pronombres relativos",
    notes: "termino gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-interrogativpronomen",
    term: "Interrogativpronomen",
    translation: "pronombres interrogativos",
    notes: "termino gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indefinitpronomen",
    term: "Indefinitpronomen",
    translation: "pronombres indefinidos",
    notes: "termino gramatical",
    context: ["A1", "sustantivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
]

export default memory
