const memory = [
  {
    id: "de-ich",
    term: "ich",
    translation: "yo",
    notes: "pronombre personal primera persona singular",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-haben",
    term: "haben",
    translation: "tener",
    notes: "verbo auxiliar",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-mein",
    term: "mein",
    translation: "mi",
    notes: "pronombre posesivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-sein",
    term: "sein",
    translation: "ser/estar",
    notes: "verbo, también 'su' (posesivo)",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-war",
    term: "war",
    translation: "era/estaba",
    notes: "pasado de sein",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-ist",
    term: "ist",
    translation: "es/está",
    notes: "tercera persona singular de sein",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-ein",
    term: "ein",
    translation: "un/uno",
    notes: "artículo indefinido masculino/neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-der",
    term: "der",
    translation: "el",
    notes: "artículo definido masculino nominativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-die",
    term: "die",
    translation: "la/las",
    notes: "artículo definido femenino/plural",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-das",
    term: "das",
    translation: "el/lo",
    notes: "artículo definido neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-nicht",
    term: "nicht",
    translation: "no",
    notes: "negación",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-so",
    term: "so",
    translation: "así/tan",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-bei",
    term: "bei",
    translation: "en/con/cerca de",
    notes: "preposición + dativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-uns",
    term: "uns",
    translation: "nos/nosotros",
    notes: "pronombre primera persona plural",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-in",
    term: "in",
    translation: "en",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-nur",
    term: "nur",
    translation: "solo/solamente",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-für",
    term: "für",
    translation: "para",
    notes: "preposición + acusativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-mit",
    term: "mit",
    translation: "con",
    notes: "preposición + dativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-mir",
    term: "mir",
    translation: "me/a mí",
    notes: "pronombre dativo primera persona singular",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-er",
    term: "er",
    translation: "él",
    notes: "pronombre tercera persona masculino singular",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-und",
    term: "und",
    translation: "y",
    notes: "conjunción",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-oft",
    term: "oft",
    translation: "a menudo",
    notes: "adverbio de frecuencia",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-als",
    term: "als",
    translation: "que/cuando",
    notes: "conjunción comparativa/temporal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-aber",
    term: "aber",
    translation: "pero",
    notes: "conjunción adversativa",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-fahren",
    term: "fahren",
    translation: "conducir/viajar",
    notes: "verbo de movimiento",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-gerne",
    term: "gerne",
    translation: "con gusto",
    notes: "adverbio, expresa gusto",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-also",
    term: "also",
    translation: "entonces/así que",
    notes: "adverbio conectivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-was",
    term: "was",
    translation: "qué",
    notes: "pronombre interrogativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-aus",
    term: "aus",
    translation: "de/desde",
    notes: "preposición + dativo, origen",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-über",
    term: "über",
    translation: "sobre/acerca de",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-nach",
    term: "nach",
    translation: "después/hacia",
    notes: "preposición + dativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-links",
    term: "links",
    translation: "izquierda",
    notes: "adverbio de dirección",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-eine",
    term: "eine",
    translation: "una",
    notes: "artículo indefinido femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-kommen",
    term: "kommen",
    translation: "venir",
    notes: "verbo de movimiento",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-groß",
    term: "groß",
    translation: "grande",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-gut",
    term: "gut",
    translation: "bueno",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-an",
    term: "an",
    translation: "en/junto a",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-zwei",
    term: "zwei",
    translation: "dos",
    notes: "número",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-wir",
    term: "wir",
    translation: "nosotros",
    notes: "pronombre primera persona plural",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-auf",
    term: "auf",
    translation: "sobre/en",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-hören",
    term: "hören",
    translation: "oír/escuchar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-lang",
    term: "lang",
    translation: "largo",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-haar",
    term: "Haar",
    translation: "cabello/pelo",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-haare",
    term: "Haare",
    translation: "cabellos",
    notes: "plural de Haar",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-brille",
    term: "Brille",
    translation: "gafas",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-kopf",
    term: "Kopf",
    translation: "cabeza",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-größer",
    term: "größer",
    translation: "más grande",
    notes: "comparativo de groß",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-bin",
    term: "bin",
    translation: "soy/estoy",
    notes: "primera persona singular de sein",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-zurück",
    term: "zurück",
    translation: "atrás/de vuelta",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-gehen",
    term: "gehen",
    translation: "ir",
    notes: "verbo de movimiento",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-wie",
    term: "wie",
    translation: "cómo",
    notes: "adverbio interrogativo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-um",
    term: "um",
    translation: "alrededor/a",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-nächste",
    term: "nächste",
    translation: "próximo/siguiente",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-greifen",
    term: "greifen",
    translation: "agarrar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-rechts",
    term: "rechts",
    translation: "derecha",
    notes: "adverbio de dirección",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-arm",
    term: "Arm",
    translation: "brazo",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-packen",
    term: "packen",
    translation: "agarrar/empacar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-zu",
    term: "zu",
    translation: "a/hacia",
    notes: "preposición",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-auge",
    term: "Auge",
    translation: "ojo",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-augen",
    term: "Augen",
    translation: "ojos",
    notes: "plural de Auge",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-auch",
    term: "auch",
    translation: "también",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-sagen",
    term: "sagen",
    translation: "decir",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-hoffentlich",
    term: "hoffentlich",
    translation: "ojalá/con suerte",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-ganz",
    term: "ganz",
    translation: "completamente/todo",
    notes: "adverbio/adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-ruhig",
    term: "ruhig",
    translation: "tranquilo/calmado",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-im",
    term: "im",
    translation: "en el",
    notes: "contracción de in + dem",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-film",
    term: "Film",
    translation: "película",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-vielleicht",
    term: "vielleicht",
    translation: "quizás/tal vez",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-wollen",
    term: "wollen",
    translation: "querer",
    notes: "verbo modal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-willst",
    term: "willst",
    translation: "quieres",
    notes: "segunda persona singular de wollen",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-du",
    term: "du",
    translation: "tú",
    notes: "pronombre segunda persona singular",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-versuchen",
    term: "versuchen",
    translation: "intentar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-noch",
    term: "noch",
    translation: "todavía/aún",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-immer",
    term: "immer",
    translation: "siempre",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-dann",
    term: "dann",
    translation: "entonces/luego",
    notes: "adverbio temporal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-auf-einmal",
    term: "auf einmal",
    translation: "de repente",
    notes: "expresión adverbial",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-hilfe",
    term: "Hilfe",
    translation: "ayuda",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-lassen",
    term: "lassen",
    translation: "dejar/permitir",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-loslasse",
    term: "loslasse",
    translation: "suelte",
    notes: "primera persona subjuntivo de loslassen",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-nie",
    term: "nie",
    translation: "nunca",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-selbst",
    term: "selbst",
    translation: "mismo/incluso",
    notes: "pronombre reflexivo/adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-damals",
    term: "damals",
    translation: "en aquel entonces",
    notes: "adverbio temporal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-sekunde",
    term: "Sekunde",
    translation: "segundo",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-drei",
    term: "drei",
    translation: "tres",
    notes: "número",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-können",
    term: "können",
    translation: "poder",
    notes: "verbo modal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-könnte",
    term: "könnte",
    translation: "podría",
    notes: "condicional de können",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-wieder",
    term: "wieder",
    translation: "otra vez/de nuevo",
    notes: "adverbio",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-vorne",
    term: "vorne",
    translation: "adelante",
    notes: "adverbio de lugar",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-beide",
    term: "beide",
    translation: "ambos",
    notes: "pronombre/adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-hand",
    term: "Hand",
    translation: "mano",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-händen",
    term: "Händen",
    translation: "manos",
    notes: "dativo plural de Hand",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-los",
    term: "los",
    translation: "vamos/adelante",
    notes: "interjección",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-erzählen",
    term: "erzählen",
    translation: "contar/narrar",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-erzähl",
    term: "erzähl",
    translation: "cuenta",
    notes: "imperativo de erzählen",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-einen",
    term: "einen",
    translation: "un/uno",
    notes: "acusativo masculino de ein",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-großen",
    term: "großen",
    translation: "grande",
    notes: "forma declinada de groß",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-licht",
    term: "Licht",
    translation: "luz",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-sich",
    term: "sich",
    translation: "se",
    notes: "pronombre reflexivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-machen",
    term: "machen",
    translation: "hacer",
    notes: "verbo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-sie",
    term: "Sie",
    translation: "usted/ustedes",
    notes: "pronombre formal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-denn",
    term: "denn",
    translation: "pues/porque",
    notes: "conjunción/partícula modal",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-da",
    term: "da",
    translation: "ahí/allí",
    notes: "adverbio de lugar",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-strichmännchen",
    term: "Strichmännchen",
    translation: "muñeco de palitos",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-hitze",
    term: "Hitze",
    translation: "calor",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-speiseröhre",
    term: "Speiseröhre",
    translation: "esófago",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-eckig",
    term: "eckig",
    translation: "angular/cuadrado",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-abgehackt",
    term: "abgehackt",
    translation: "entrecortado/abrupto",
    notes: "adjetivo, participio de abhacken",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-schlägerei",
    term: "Schlägerei",
    translation: "pelea/riña",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-reh",
    term: "Reh",
    translation: "corzo",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-autoscheinwerfer",
    term: "Autoscheinwerfer",
    translation: "faro de coche",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-fett",
    term: "fett",
    translation: "gordo/grasoso",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-aufhören",
    term: "aufhören",
    translation: "parar/dejar de",
    notes: "verbo separable",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-faust",
    term: "Faust",
    translation: "puño",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-niere",
    term: "Niere",
    translation: "riñón",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-steuer",
    term: "Steuer",
    translation: "impuesto/volante",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-vorletzt",
    term: "vorletzt",
    translation: "penúltimo",
    notes: "adjetivo; uso: vorletzter Waggon",
    context: ["A1", "A2", "B2"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-hart",
    term: "hart",
    translation: "duro",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-rücken",
    term: "Rücken",
    translation: "espalda",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-magen",
    term: "Magen",
    translation: "estómago",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-seltsam",
    term: "seltsam",
    translation: "extraño",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-leid",
    term: "Leid",
    translation: "sufrimiento",
    notes: "sustantivo neutro",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-angst",
    term: "Angst",
    translation: "miedo/ansiedad",
    notes: "sustantivo femenino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-überfall",
    term: "Überfall",
    translation: "atraco/asalto",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-fair",
    term: "fair",
    translation: "justo",
    notes: "adjetivo",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },
  {
    id: "de-held",
    term: "Held",
    translation: "héroe",
    notes: "sustantivo masculino",
    context: ["A1"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:30:00.000Z",
    learningState: "LEARNED",
  },

  {
    id: "de-erst",
    term: "erst",
    translation: "primero/recién",
    notes: "adverbio temporal",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-klein",
    term: "klein",
    translation: "pequeño",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-eigentlich",
    term: "eigentlich",
    translation: "en realidad/realmente",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-holen",
    term: "holen",
    translation: "buscar/traer",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-meinen",
    term: "meinen",
    translation: "opinar/pensar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-bulle",
    term: "Bulle",
    translation: "policía (coloquial)",
    notes: "sustantivo masculino, también significa 'toro'",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-bullen",
    term: "Bullen",
    translation: "policías",
    notes: "plural de Bulle",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-kontrollieren",
    term: "kontrollieren",
    translation: "controlar/revisar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-einfach",
    term: "einfach",
    translation: "simple/simplemente",
    notes: "adjetivo/adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-faul",
    term: "faul",
    translation: "perezoso/flojo",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-sack",
    term: "Sack",
    translation: "saco",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-bahnhof",
    term: "Bahnhof",
    translation: "estación de tren",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-kreuzung",
    term: "Kreuzung",
    translation: "cruce/intersección",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-straße",
    term: "Straße",
    translation: "calle",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-friedhof",
    term: "Friedhof",
    translation: "cementerio",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-etwa",
    term: "etwa",
    translation: "aproximadamente",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schätzen",
    term: "schätzen",
    translation: "estimar/valorar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-oben",
    term: "oben",
    translation: "arriba",
    notes: "adverbio de lugar",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-typ",
    term: "Typ",
    translation: "tipo/tío",
    notes: "sustantivo masculino, coloquial para persona",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schwarz",
    term: "schwarz",
    translation: "negro",
    notes: "adjetivo/color",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schulter",
    term: "Schulter",
    translation: "hombro",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-komplett",
    term: "komplett",
    translation: "completo/completamente",
    notes: "adjetivo/adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-leder",
    term: "Leder",
    translation: "cuero",
    notes: "sustantivo neutro",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-unten",
    term: "unten",
    translation: "abajo",
    notes: "adverbio de lugar",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-gucken",
    term: "gucken",
    translation: "mirar",
    notes: "verbo, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-gleich",
    term: "gleich",
    translation: "igual/enseguida",
    notes: "adjetivo/adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-höhe",
    term: "Höhe",
    translation: "altura",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-flauschig",
    term: "flauschig",
    translation: "esponjoso/suave",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-stoff",
    term: "Stoff",
    translation: "tela/material",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-steigen",
    term: "steigen",
    translation: "subir/escalar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-gehirn",
    term: "Gehirn",
    translation: "cerebro",
    notes: "sustantivo neutro",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-welt",
    term: "Welt",
    translation: "mundo",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-neben",
    term: "neben",
    translation: "al lado de",
    notes: "preposición + dativo/acusativo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-drehen",
    term: "drehen",
    translation: "girar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-laufen",
    term: "laufen",
    translation: "correr/caminar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-hinterher",
    term: "hinterher",
    translation: "detrás/después",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-ampel",
    term: "Ampel",
    translation: "semáforo",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-oberarm",
    term: "Oberarm",
    translation: "parte superior del brazo",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-reißen",
    term: "reißen",
    translation: "arrancar/romper",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-herum",
    term: "herum",
    translation: "alrededor",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-dunkelgrün",
    term: "dunkelgrün",
    translation: "verde oscuro",
    notes: "adjetivo/color",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-wünschen",
    term: "wünschen",
    translation: "desear",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-laut",
    term: "laut",
    translation: "fuerte/ruidoso",
    notes: "adjetivo/adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-brüllen",
    term: "brüllen",
    translation: "gritar/rugir",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schwul",
    term: "schwul",
    translation: "gay",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-festhalten",
    term: "festhalten",
    translation: "sujetar/agarrar fuerte",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schreien",
    term: "schreien",
    translation: "gritar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-überrascht",
    term: "überrascht",
    translation: "sorprendido",
    notes: "adjetivo, participio de überraschen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-mann",
    term: "Mann",
    translation: "hombre",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-bein",
    term: "Bein",
    translation: "pierna",
    notes: "sustantivo neutro",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-beinen",
    term: "Beinen",
    translation: "piernas",
    notes: "dativo plural de Bein",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-judenwitz",
    term: "Judenwitz",
    translation: "chiste sobre judíos",
    notes: "sustantivo masculino, término sensible",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-zählen",
    term: "zählen",
    translation: "contar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-krallen",
    term: "krallen",
    translation: "agarrar con las uñas",
    notes: "verbo reflexivo: sich krallen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-ballen",
    term: "ballen",
    translation: "apretar/formar bola",
    notes: "verbo reflexivo: sich ballen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-hochsteigen",
    term: "hochsteigen",
    translation: "subir/ascender",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-flippen",
    term: "flippen",
    translation: "flipar/enloquecer",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-losrennen",
    term: "losrennen",
    translation: "echar a correr",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-überrumpeln",
    term: "überrumpeln",
    translation: "sorprender/abrumar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schütteln",
    term: "schütteln",
    translation: "sacudir/agitar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schiffbrüchiger",
    term: "Schiffbrüchiger",
    translation: "náufrago",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-treffen",
    term: "treffen",
    translation: "encontrar/acertar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-fallen",
    term: "fallen",
    translation: "caer",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-aufwachen",
    term: "aufwachen",
    translation: "despertarse",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-stecken",
    term: "stecken",
    translation: "meter/estar atascado",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-jedenfalls",
    term: "jedenfalls",
    translation: "en todo caso",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-handballen",
    term: "Handballen",
    translation: "palma de la mano",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-verwirrt",
    term: "verwirrt",
    translation: "confundido",
    notes: "adjetivo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-krümmen",
    term: "krümmen",
    translation: "encorvarse/retorcerse",
    notes: "verbo reflexivo: sich krümmen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-wiegen",
    term: "wiegen",
    translation: "pesar/mecer",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-knacksen",
    term: "knacksen",
    translation: "crujir",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-walnuss",
    term: "Walnuss",
    translation: "nuez",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-rammen",
    term: "rammen",
    translation: "embestir/empotrar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-hallen",
    term: "hallen",
    translation: "resonar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-rutschen",
    term: "rutschen",
    translation: "resbalar/deslizar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-quetschen",
    term: "quetschen",
    translation: "aplastar/estrujar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-breitbeinig",
    term: "breitbeinig",
    translation: "con las piernas abiertas",
    notes: "adjetivo/adverbio",
    context: ["A2", "B2"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-bilden",
    term: "bilden",
    translation: "formar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schützend",
    term: "schützend",
    translation: "protector",
    notes: "adjetivo, participio de schützen",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-rüstung",
    term: "Rüstung",
    translation: "armadura",
    notes: "sustantivo femenino",
    context: ["A2", "B2"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-ausholen",
    term: "ausholen",
    translation: "echarse atrás para golpear",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-ansehen",
    term: "ansehen",
    translation: "mirar/parecer",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-angucken",
    term: "angucken",
    translation: "mirar",
    notes: "verbo separable, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-fressen",
    term: "fressen",
    translation: "comer (animales)/devorar",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-schließlich",
    term: "schließlich",
    translation: "finalmente",
    notes: "adverbio",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-mitfahren",
    term: "mitfahren",
    translation: "ir con/acompañar",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-tippen",
    term: "tippen",
    translation: "teclear/tocar ligeramente",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-aussage",
    term: "Aussage",
    translation: "declaración",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-anzeigen",
    term: "anzeigen",
    translation: "denunciar/mostrar",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-rechtsschutzversicherung",
    term: "Rechtsschutzversicherung",
    translation: "seguro de defensa jurídica",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-gericht",
    term: "Gericht",
    translation: "tribunal/plato",
    notes: "sustantivo neutro",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-wehren",
    term: "wehren",
    translation: "defenderse",
    notes: "verbo reflexivo: sich wehren",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-katzensatt",
    term: "katzensatt",
    translation: "llenísimo",
    notes: "adjetivo, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-verdreschen",
    term: "verdreschen",
    translation: "apalear",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-retten",
    term: "retten",
    translation: "rescatar/salvar",
    notes: "verbo; participio: gerettet",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-weglaufen",
    term: "weglaufen",
    translation: "huir/irse corriendo",
    notes: "verbo separable",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-einzelheit",
    term: "Einzelheit",
    translation: "detalle",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-vergebung",
    term: "Vergebung",
    translation: "perdón",
    notes: "sustantivo femenino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-priester",
    term: "Priester",
    translation: "sacerdote",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-tacken",
    term: "Tacken",
    translation: "tachuela/clavo pequeño",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-klären",
    term: "klären",
    translation: "aclarar/resolver",
    notes: "verbo",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-scheiß",
    term: "Scheiß",
    translation: "mierda",
    notes: "sustantivo masculino, vulgar",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-feigling",
    term: "Feigling",
    translation: "cobarde",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-die-klappe-halten",
    term: "die Klappe halten",
    translation: "callarse/cerrar la boca",
    notes: "expresión verbal, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-tausch",
    term: "Tausch",
    translation: "intercambio",
    notes: "sustantivo masculino",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-eine-reinziehen",
    term: "eine reinziehen",
    translation: "dar un golpe",
    notes: "expresión verbal, coloquial",
    context: ["A2"],
    contextForPractice: [],
    baseScore: 5,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:35:00.000Z",
    learningState: "LEARNING_2",
  },
  {
    id: "de-verfilzt",
    term: "verfilzt",
    translation: "enmarañado/afieltrado",
    notes: "adjetivo, participio de verfilzen",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-bunt",
    term: "bunt",
    translation: "colorido",
    notes: "adjetivo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-häkeln",
    term: "häkeln",
    translation: "hacer ganchillo",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-pflanzen",
    term: "pflanzen",
    translation: "plantar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-sich-ducken",
    term: "sich ducken",
    translation: "agacharse",
    notes: "verbo reflexivo: sich ducken",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-bescheuert",
    term: "bescheuert",
    translation: "estúpido",
    notes: "adjetivo, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-poltern",
    term: "poltern",
    translation: "retumbar/armar ruido",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-erwischen",
    term: "erwischen",
    translation: "atrapar/pillar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-riesenreifen",
    term: "Riesenreifen",
    translation: "neumático gigante",
    notes: "sustantivo masculino",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-fuchteln",
    term: "fuchteln",
    translation: "agitar los brazos",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-sprinten",
    term: "sprinten",
    translation: "esprintar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-sich-quetschen",
    term: "sich quetschen",
    translation: "apretujarse",
    notes: "verbo reflexivo: sich quetschen",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-zuschnappen",
    term: "zuschnappen",
    translation: "cerrarse de golpe/morder",
    notes: "verbo separable",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-aufreißen",
    term: "aufreißen",
    translation: "rasgar/abrir de golpe",
    notes: "verbo separable",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-seinesgleichen",
    term: "seinesgleichen",
    translation: "de su calaña/iguales",
    notes: "pronombre/sustantivo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-tänzeln",
    term: "tänzeln",
    translation: "danzar/andar dando saltitos",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-zimmern",
    term: "zimmern",
    translation: "carpintear/armar",
    notes: "verbo, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-sacken",
    term: "sacken",
    translation: "hundirse/asentarse",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-drankommen",
    term: "drankommen",
    translation: "tocar el turno/llegar",
    notes: "verbo, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-riskant",
    term: "riskant",
    translation: "arriesgado",
    notes: "adjetivo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-hampelmann",
    term: "Hampelmann",
    translation: "muñeco articulado",
    notes: "sustantivo masculino",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-kopfhaut",
    term: "Kopfhaut",
    translation: "cuero cabelludo",
    notes: "sustantivo femenino",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-abziehen",
    term: "abziehen",
    translation: "quitar/arrancar",
    notes: "verbo separable",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-taumeln",
    term: "taumeln",
    translation: "tambalearse",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-riesengewese",
    term: "Riesengewese",
    translation: "gran alboroto",
    notes: "sustantivo neutro, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-verfrachten",
    term: "verfrachten",
    translation: "transportar/cargar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-lauern",
    term: "lauern",
    translation: "acechar",
    notes: "verbo",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
  {
    id: "de-hinkriegen",
    term: "hinkriegen",
    translation: "conseguir/arreglar",
    notes: "verbo, coloquial",
    context: ["B1"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
    learningState: "SAVED",
  },
]
