const otras = [
  {
    id: "de-noun-flair",
    term: "Flair",
    translation: "el estilo, el ambiente, el encanto",
    notes: "sustantivo neutro - atmósfera especial o elegancia",
    context: ["B2", "sustantivo", "neutro", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-bordell",
    term: "Bordell",
    translation: "el burdel, el prostíbulo",
    notes: "sustantivo neutro - establecimiento de prostitución",
    context: ["C1", "sustantivo", "neutro", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-prep-seit",
    term: "seit",
    translation: "desde",
    notes: "preposición temporal - indica inicio de periodo (+ dativo)",
    context: ["A1", "preposicion", "temporal"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-num-30",
    term: "30",
    translation: "treinta",
    notes: "número cardinal - dreißig",
    context: ["A1", "numero", "cardinal"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-jahre-plural",
    term: "Jahren",
    translation: "años",
    notes: "sustantivo neutro plural - forma dativo de 'Jahre'",
    context: ["A1", "sustantivo", "neutro", "plural", "dativo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-schoenste",
    term: "schönste",
    translation: "más bonito/a, el/la más hermoso/a",
    notes: "adjetivo superlativo - forma declinada de 'schönst-'",
    context: ["A2", "adjetivo", "superlativo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-erotische",
    term: "erotische",
    translation: "erótico/a",
    notes: "adjetivo - forma declinada de 'erotisch'",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-zimmervermietung",
    term: "Zimmervermietung",
    translation: "alquiler de habitaciones",
    notes: "sustantivo femenino compuesto - Zimmer (habitación) + Vermietung (alquiler)",
    context: ["B1", "sustantivo", "femenino", "singular", "compuesto"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-weissensee",
    term: "Weißensee",
    translation: "Weißensee",
    notes: "nombre propio - barrio de Berlín",
    context: ["A1", "nombre-propio", "lugar"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-vermieten",
    term: "vermieten",
    translation: "alquilar (como arrendador)",
    notes: "verbo separable - dar en alquiler",
    context: ["A2", "verbo", "infinitivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-zimmer",
    term: "Zimmer",
    translation: "la habitación, el cuarto",
    notes: "sustantivo neutro - igual en singular y plural",
    context: ["A1", "sustantivo", "neutro", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-kuerzere",
    term: "kürzere",
    translation: "más cortos/cortas",
    notes: "adjetivo comparativo - forma declinada de 'kürzer'",
    context: ["A2", "adjetivo", "comparativo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-zeitraeume",
    term: "Zeiträume",
    translation: "periodos, lapsos de tiempo",
    notes: "sustantivo masculino plural - Zeitraum en plural",
    context: ["B1", "sustantivo", "masculino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-paare",
    term: "Paare",
    translation: "parejas",
    notes: "sustantivo neutro plural - Paar en plural",
    context: ["A1", "sustantivo", "neutro", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-conj-oder",
    term: "oder",
    translation: "o",
    notes: "conjunción coordinante - alternativa",
    context: ["A1", "conjuncion", "coordinante"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-einzelpersonen",
    term: "Einzelpersonen",
    translation: "personas individuales, individuos",
    notes: "sustantivo femenino plural - Einzelperson en plural",
    context: ["B1", "sustantivo", "femenino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-uebernachtung",
    term: "Übernachtung",
    translation: "el alojamiento, la pernoctación",
    notes: "sustantivo femenino - pasar la noche",
    context: ["A2", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-moeglich",
    term: "möglich",
    translation: "posible",
    notes: "adjetivo - que puede hacerse",
    context: ["A2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-folgenden",
    term: "folgenden",
    translation: "siguientes",
    notes: "adjetivo - forma declinada de 'folgend'",
    context: ["A2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-seiten",
    term: "Seiten",
    translation: "páginas, lados",
    notes: "sustantivo femenino plural - Seite en plural",
    context: ["A1", "sustantivo", "femenino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-findest",
    term: "findest",
    translation: "encuentras",
    notes: "verbo 'finden' conjugado - 2ª persona singular presente",
    context: ["A1", "verbo", "presente", "segunda-persona"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-inserate",
    term: "Inserate",
    translation: "anuncios, avisos clasificados",
    notes: "sustantivo neutro plural - Inserat en plural",
    context: ["B1", "sustantivo", "neutro", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-prep-von",
    term: "von",
    translation: "de, desde",
    notes: "preposición - origen, posesión (+ dativo)",
    context: ["A1", "preposicion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-selbststaendig",
    term: "selbstständig",
    translation: "independiente, autónomo",
    notes: "adjetivo - que trabaja por cuenta propia",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-taetigen",
    term: "tätigen",
    translation: "activos, que ejercen",
    notes: "adjetivo/participio - forma declinada de 'tätig'",
    context: ["B2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-sexarbeiterinnen",
    term: "Sexarbeiterinnen",
    translation: "trabajadoras sexuales",
    notes: "sustantivo femenino plural - Sexarbeiterin en plural",
    context: ["C1", "sustantivo", "femenino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-beauftragt",
    term: "beauftragt",
    translation: "encargado, comisionado",
    notes: "participio pasado de 'beauftragen' - encargar",
    context: ["B2", "verbo", "participio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adv-hier-var",
    term: "hier",
    translation: "aquí",
    notes: "adverbio de lugar - en este lugar",
    context: ["A1", "adverbio", "lugar"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-werbung",
    term: "Werbung",
    translation: "la publicidad, el anuncio",
    notes: "sustantivo femenino - promoción comercial",
    context: ["A2", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-veroeffentlichen",
    term: "veröffentlichen",
    translation: "publicar",
    notes: "verbo - hacer público, editar",
    context: ["B1", "verbo", "infinitivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-geschaeftsanbahnung",
    term: "Geschäftsanbahnung",
    translation: "iniciación de negocios, gestión comercial",
    notes: "sustantivo femenino compuesto - establecimiento de contactos comerciales",
    context: ["C1", "sustantivo", "femenino", "singular", "compuesto"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-findet",
    term: "findet",
    translation: "encuentra, tiene lugar",
    notes: "verbo 'finden' conjugado - 3ª persona singular presente",
    context: ["A1", "verbo", "presente", "tercera-persona"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adv-ausschliesslich-var",
    term: "ausschließlich",
    translation: "exclusivamente",
    notes: "adverbio - únicamente, solo",
    context: ["B1", "adverbio", "modo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-inserentinnen",
    term: "Inserentinnen",
    translation: "anunciantes (femenino)",
    notes: "sustantivo femenino plural - Inserentin en plural",
    context: ["B2", "sustantivo", "femenino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-prep-statt",
    term: "statt",
    translation: "en lugar de, en vez de",
    notes: "preposición - sustitución (+ genitivo/dativo)",
    context: ["B1", "preposicion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-nimmt",
    term: "nimmt",
    translation: "toma, acepta",
    notes: "verbo 'nehmen' conjugado - 3ª persona singular presente",
    context: ["A1", "verbo", "presente", "tercera-persona", "irregular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-auftraege",
    term: "Aufträge",
    translation: "encargos, pedidos",
    notes: "sustantivo masculino plural - Auftrag en plural",
    context: ["B1", "sustantivo", "masculino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-vereinbart",
    term: "vereinbart",
    translation: "acuerda, conviene",
    notes: "participio pasado/3ª persona de 'vereinbaren' - acordar",
    context: ["B1", "verbo", "participio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-termine",
    term: "Termine",
    translation: "citas, fechas",
    notes: "sustantivo masculino plural - Termin en plural",
    context: ["A2", "sustantivo", "masculino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-interj-bitte",
    term: "Bitte",
    translation: "por favor",
    notes: "interjección/sustantivo - fórmula de cortesía",
    context: ["A1", "interjeccion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-kontaktiere",
    term: "kontaktiere",
    translation: "contacta",
    notes: "verbo 'kontaktieren' - imperativo/1ª persona singular presente",
    context: ["A2", "verbo", "imperativo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-jeweilige",
    term: "jeweilige",
    translation: "respectivo/a, correspondiente",
    notes: "adjetivo - forma declinada de 'jeweilig'",
    context: ["B2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-inserentin",
    term: "Inserentin",
    translation: "anunciante (femenino)",
    notes: "sustantivo femenino - persona que publica anuncios",
    context: ["B2", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adv-direkt",
    term: "direkt",
    translation: "directamente",
    notes: "adverbio - sin intermediarios",
    context: ["A2", "adverbio", "modo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-angegebenen",
    term: "angegebenen",
    translation: "indicados, especificados",
    notes: "participio pasado declinado de 'angeben' - indicar",
    context: ["B1", "adjetivo", "participio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-kontaktdaten",
    term: "Kontaktdaten",
    translation: "datos de contacto",
    notes: "sustantivo plural compuesto - información de contacto",
    context: ["A2", "sustantivo", "plural", "compuesto"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-preise",
    term: "Preise",
    translation: "precios",
    notes: "sustantivo masculino plural - Preis en plural",
    context: ["A1", "sustantivo", "masculino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-beinhalten",
    term: "beinhalten",
    translation: "incluir, contener",
    notes: "verbo - tener como contenido",
    context: ["B1", "verbo", "infinitivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-nutzung",
    term: "Nutzung",
    translation: "el uso, la utilización",
    notes: "sustantivo femenino - acción de usar",
    context: ["B1", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-raeumlichkeiten",
    term: "Räumlichkeiten",
    translation: "locales, instalaciones",
    notes: "sustantivo femenino plural - espacios/habitaciones",
    context: ["B2", "sustantivo", "femenino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-prep-einschliesslich",
    term: "einschließlich",
    translation: "incluido, inclusive",
    notes: "preposición - incluyendo (+ genitivo)",
    context: ["B2", "preposicion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-dusche",
    term: "Dusche",
    translation: "la ducha",
    notes: "sustantivo femenino - lugar para ducharse",
    context: ["A1", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-toilette",
    term: "Toilette",
    translation: "el baño, el inodoro",
    notes: "sustantivo femenino - servicio sanitario",
    context: ["A1", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-enthalten",
    term: "enthalten",
    translation: "contenido, incluido",
    notes: "participio pasado de 'enthalten' - contener",
    context: ["B1", "verbo", "participio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-erbrachten",
    term: "erbrachten",
    translation: "prestados, proporcionados",
    notes: "participio pasado declinado de 'erbringen' - proporcionar",
    context: ["B2", "adjetivo", "participio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-leistungen",
    term: "Leistungen",
    translation: "servicios, prestaciones",
    notes: "sustantivo femenino plural - Leistung en plural",
    context: ["B1", "sustantivo", "femenino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-besprich",
    term: "besprich",
    translation: "discute, habla sobre",
    notes: "verbo 'besprechen' - imperativo 2ª persona singular",
    context: ["B1", "verbo", "imperativo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adv-hierfuer",
    term: "hierfür",
    translation: "para esto, para ello",
    notes: "adverbio pronominal - finalidad referencial",
    context: ["B1", "adverbio", "pronominal"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-jeweiligen-var",
    term: "jeweiligen",
    translation: "respectivos, correspondientes",
    notes: "adjetivo - forma declinada dativo/acusativo de 'jeweilig'",
    context: ["B2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-persoenlich",
    term: "persönlich",
    translation: "personalmente, en persona",
    notes: "adjetivo/adverbio - de manera personal",
    context: ["A2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-prep-ab",
    term: "ab",
    translation: "desde, a partir de",
    notes: "preposición temporal/espacial - inicio (+ dativo)",
    context: ["A1", "preposicion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adv-taeglich",
    term: "täglich",
    translation: "diariamente, cada día",
    notes: "adverbio temporal - todos los días",
    context: ["A1", "adverbio", "temporal"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-prep-vor",
    term: "vor",
    translation: "delante de, antes de, ante",
    notes: "preposición - posición/tiempo (+ dativo/acusativo)",
    context: ["A1", "preposicion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-ort",
    term: "Ort",
    translation: "el lugar, el sitio",
    notes: "sustantivo masculino - localización, sitio",
    context: ["A1", "sustantivo", "masculino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-bitten",
    term: "bitten",
    translation: "pedir, rogar",
    notes: "verbo irregular - solicitar",
    context: ["A2", "verbo", "infinitivo", "irregular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-termin",
    term: "Termin",
    translation: "la cita, la fecha",
    notes: "sustantivo masculino - hora acordada",
    context: ["A2", "sustantivo", "masculino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-vereinbaren",
    term: "vereinbaren",
    translation: "acordar, pactar",
    notes: "verbo - llegar a un acuerdo",
    context: ["B1", "verbo", "infinitivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-inhalte",
    term: "Inhalte",
    translation: "contenidos",
    notes: "sustantivo masculino plural - Inhalt en plural",
    context: ["B1", "sustantivo", "masculino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-fotos",
    term: "Fotos",
    translation: "fotos, fotografías",
    notes: "sustantivo neutro plural - Foto en plural",
    context: ["A1", "sustantivo", "neutro", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-verantwortlich",
    term: "verantwortlich",
    translation: "responsable",
    notes: "adjetivo - que tiene responsabilidad",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-uebernimmt",
    term: "übernimmt",
    translation: "asume, se hace cargo",
    notes: "verbo 'übernehmen' conjugado - 3ª persona singular presente",
    context: ["B1", "verbo", "presente", "tercera-persona"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-haftung",
    term: "Haftung",
    translation: "la responsabilidad, la garantía",
    notes: "sustantivo femenino - responsabilidad legal",
    context: ["B2", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-einzelnen",
    term: "einzelnen",
    translation: "individuales, particulares",
    notes: "adjetivo - forma declinada de 'einzeln'",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-gemachten",
    term: "gemachten",
    translation: "hechos, realizados",
    notes: "participio pasado declinado de 'machen' - hacer",
    context: ["A2", "adjetivo", "participio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-angaben",
    term: "Angaben",
    translation: "indicaciones, datos, información",
    notes: "sustantivo femenino plural - Angabe en plural",
    context: ["B1", "sustantivo", "femenino", "plural"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },

  {
    id: "de-adj-lieber",
    term: "Lieber",
    translation: "querido, estimado",
    notes: "adjetivo - forma de saludo (masculino nominativo)",
    context: ["A1", "adjetivo", "saludo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-name",
    term: "Name",
    translation: "el nombre",
    notes: "sustantivo masculino - denominación de persona o cosa",
    context: ["A1", "sustantivo", "masculino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-name-kira",
    term: "Kira",
    translation: "Kira",
    notes: "nombre propio femenino",
    context: ["A1", "nombre-propio", "persona"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:42:45.346Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-num-29",
    term: "29",
    translation: "veintinueve",
    notes: "número cardinal - neunundzwanzig",
    context: ["A1", "numero", "cardinal"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:42:50.237Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-jahre",
    term: "Jahre",
    translation: "años",
    notes: "sustantivo neutro plural - plural de 'Jahr'",
    context: ["A1", "sustantivo", "neutro", "plural"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:42:57.066Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-alt",
    term: "alt",
    translation: "viejo, antiguo",
    notes: "adjetivo - de edad avanzada o antigüedad",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:43:00.970Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-spanien",
    term: "Spanien",
    translation: "España",
    notes: "nombre propio - país europeo",
    context: ["A1", "nombre-propio", "pais"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:43:06.688Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adv-sehr-var",
    term: "sehr",
    translation: "muy",
    notes: "adverbio de grado - intensificación alta",
    context: ["A1", "adverbio", "grado"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-aufgeschlossen",
    term: "aufgeschlossen",
    translation: "abierto (de mente), receptivo",
    notes: "adjetivo/participio - de mentalidad abierta",
    context: ["B1", "adjetivo", "personalidad"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: "2025-12-27T14:43:20.730Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-erotischen-var",
    term: "erotischen",
    translation: "erótico/a",
    notes: "adjetivo - forma declinada dativo de 'erotisch'",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-anzeigentext",
    term: "Anzeigentext",
    translation: "texto del anuncio",
    notes: "sustantivo masculino compuesto - Anzeige (anuncio) + Text (texto)",
    context: ["B1", "sustantivo", "masculino", "singular", "compuesto"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-gebe",
    term: "gebe",
    translation: "doy",
    notes: "verbo 'geben' conjugado - 1ª persona singular presente",
    context: ["A1", "verbo", "presente", "primera-persona"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-kleinen",
    term: "kleinen",
    translation: "pequeño/a",
    notes: "adjetivo - forma declinada de 'klein'",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-vorgeschmack",
    term: "Vorgeschmack",
    translation: "adelanto, anticipo, muestra previa",
    notes: "sustantivo masculino - sabor anticipado, primer indicio",
    context: ["B2", "sustantivo", "masculino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-prep-von-var",
    term: "von",
    translation: "de, desde",
    notes: "preposición - origen, posesión (+ dativo)",
    context: ["A1", "preposicion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-erwarten",
    term: "erwarten",
    translation: "esperar, aguardar",
    notes: "verbo - anticipar que algo suceda",
    context: ["A2", "verbo", "infinitivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-kannst",
    term: "kannst",
    translation: "puedes",
    notes: "verbo modal 'können' conjugado - 2ª persona singular presente",
    context: ["A1", "verbo", "modal", "presente", "segunda-persona"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:44:55.513Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-lustige",
    term: "lustige",
    translation: "divertido/a, gracioso/a",
    notes: "adjetivo - forma declinada de 'lustig'",
    context: ["A2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-flirty",
    term: "flirty",
    translation: "coqueto/a, seductor/a",
    notes: "adjetivo (anglicismo) - que flirtea",
    context: ["B1", "adjetivo", "anglicismo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-heisse",
    term: "heiße",
    translation: "caliente, ardiente",
    notes: "adjetivo - forma declinada de 'heiß'",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-lady",
    term: "Lady",
    translation: "dama, señora",
    notes: "sustantivo femenino (anglicismo) - mujer elegante",
    context: ["A2", "sustantivo", "femenino", "singular", "anglicismo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-conj-wenn",
    term: "Wenn",
    translation: "si, cuando",
    notes: "conjunción subordinante - condición/tiempo",
    context: ["A1", "conjuncion", "subordinante"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:43:47.923Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-suche",
    term: "Suche",
    translation: "la búsqueda",
    notes: "sustantivo femenino - acción de buscar",
    context: ["A2", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 7,
    lastPracticedAt: "2025-12-27T14:43:54.936Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-unvergesslichen",
    term: "unvergesslichen",
    translation: "inolvidable",
    notes: "adjetivo - forma declinada de 'unvergesslich'",
    context: ["B2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-erlebnis",
    term: "Erlebnis",
    translation: "la experiencia, la vivencia",
    notes: "sustantivo neutro - acontecimiento memorable",
    context: ["B1", "sustantivo", "neutro", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-bist",
    term: "bist",
    translation: "eres, estás",
    notes: "verbo 'sein' conjugado - 2ª persona singular presente",
    context: ["A1", "verbo", "presente", "segunda-persona", "irregular"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:44:12.942Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-richtig-var",
    term: "richtig",
    translation: "correcto, adecuado",
    notes: "adjetivo - que es como debe ser",
    context: ["A1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-weiss",
    term: "weiß",
    translation: "sé, sabe",
    notes: "verbo 'wissen' conjugado - 1ª/3ª persona singular presente",
    context: ["A1", "verbo", "presente", "irregular"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:44:33.071Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-besorgt",
    term: "besorgt",
    translation: "preocupado / consigue",
    notes: "adjetivo/participio - preocupado o conseguir/comprar",
    context: ["A2", "verbo", "participio"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-spezialitaet",
    term: "Spezialität",
    translation: "la especialidad",
    notes: "sustantivo femenino - algo en lo que se destaca",
    context: ["B1", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-interj-mmm",
    term: "mmm",
    translation: "mmm",
    notes: "interjección - expresión de placer o reflexión",
    context: ["A1", "interjeccion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-versuch",
    term: "versuch",
    translation: "intenta",
    notes: "verbo 'versuchen' - imperativo 2ª persona singular",
    context: ["A2", "verbo", "imperativo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-erraten",
    term: "erraten",
    translation: "adivinar, acertar",
    notes: "verbo - descubrir por intuición",
    context: ["B1", "verbo", "infinitivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adv-ausserdem",
    term: "Außerdem",
    translation: "además, por otra parte",
    notes: "adverbio - para añadir información",
    context: ["A2", "adverbio", "conexion"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:44:50.569Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-zusaetzlichen",
    term: "zusätzlichen",
    translation: "adicionales, extras",
    notes: "adjetivo - forma declinada de 'zusätzlich'",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-services",
    term: "Services",
    translation: "servicios",
    notes: "sustantivo plural (anglicismo) - prestaciones",
    context: ["B1", "sustantivo", "plural", "anglicismo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-anspruch",
    term: "Anspruch",
    translation: "la exigencia, la pretensión",
    notes: "sustantivo masculino - derecho o demanda",
    context: ["B2", "sustantivo", "masculino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-nehmen",
    term: "nehmen",
    translation: "tomar, coger",
    notes: "verbo irregular - agarrar o usar",
    context: ["A1", "verbo", "infinitivo", "irregular"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:45:14.635Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-prep-zum",
    term: "zum",
    translation: "al, para el",
    notes: "contracción - zu + dem (preposición + artículo dativo masculino/neutro)",
    context: ["A1", "preposicion", "contraccion"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-beispiel",
    term: "Beispiel",
    translation: "el ejemplo",
    notes: "sustantivo neutro - muestra o caso ilustrativo",
    context: ["A1", "sustantivo", "neutro", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-koerperkuesse",
    term: "Körperküsse",
    translation: "besos corporales",
    notes: "sustantivo masculino plural compuesto - Körper (cuerpo) + Küsse (besos)",
    context: ["B2", "sustantivo", "masculino", "plural", "compuesto"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-kuscheln",
    term: "Kuscheln",
    translation: "acurrucarse, abrazar",
    notes: "verbo sustantivado - acción de acariciarse",
    context: ["A2", "verbo", "sustantivado"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-fingern",
    term: "Fingern",
    translation: "estimulación manual",
    notes: "verbo sustantivado - de 'fingern' (uso de dedos)",
    context: ["C1", "verbo", "sustantivado"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-dildospiele",
    term: "Dildospiele",
    translation: "juegos con dildo",
    notes: "sustantivo neutro plural compuesto - Dildo + Spiele (juegos)",
    context: ["C1", "sustantivo", "neutro", "plural", "compuesto"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-happyend-massage",
    term: "HappyEnd-Massage",
    translation: "masaje con final feliz",
    notes: "sustantivo femenino compuesto (anglicismo) - masaje erótico",
    context: ["C1", "sustantivo", "femenino", "singular", "compuesto", "anglicismo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-einfuehlsam",
    term: "einfühlsam",
    translation: "empático, comprensivo",
    notes: "adjetivo - que muestra empatía",
    context: ["B2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-werde",
    term: "werde",
    translation: "seré, me convertiré",
    notes: "verbo 'werden' conjugado - 1ª persona singular futuro/presente",
    context: ["A2", "verbo", "futuro", "primera-persona"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: "2025-12-27T14:45:42.466Z",
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-behilflich",
    term: "behilflich",
    translation: "servicial, útil",
    notes: "adjetivo - dispuesto a ayudar",
    context: ["B1", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-lass",
    term: "Lass",
    translation: "deja, permite",
    notes: "verbo 'lassen' - imperativo 2ª persona singular",
    context: ["A1", "verbo", "imperativo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-nacht",
    term: "Nacht",
    translation: "la noche",
    notes: "sustantivo femenino - periodo de oscuridad",
    context: ["A1", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-adj-voller",
    term: "voller",
    translation: "lleno de",
    notes: "adjetivo - forma declinada genitiva de 'voll'",
    context: ["A2", "adjetivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-leidenschaft",
    term: "Leidenschaft",
    translation: "la pasión",
    notes: "sustantivo femenino - sentimiento intenso",
    context: ["B1", "sustantivo", "femenino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-noun-genuss",
    term: "Genuss",
    translation: "el placer, el disfrute",
    notes: "sustantivo masculino - goce o deleite",
    context: ["B1", "sustantivo", "masculino", "singular"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
  {
    id: "de-verb-erleben",
    term: "erleben",
    translation: "experimentar, vivir",
    notes: "verbo - tener una experiencia",
    context: ["A2", "verbo", "infinitivo"],
    contextForPractice: [],
    baseScore: 0,
    lastPracticedAt: null,
    createdAt: "2025-12-27T00:00:00.000Z",
  },
]

export default otras
