const pronombres = [
  // ========== PRONOMBRES PERSONALES - NOMINATIV ==========
  {
    id: "de-pron-ich-nom",
    term: "ich",
    translation: "yo",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "ich"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-du-nom",
    term: "du",
    translation: "tú",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "du"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-er-nom",
    term: "er",
    translation: "él",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "er"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-nom",
    term: "sie",
    translation: "ella",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "sie"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-es-nom",
    term: "es",
    translation: "ello",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "es"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-wir-nom",
    term: "wir",
    translation: "nosotros",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "wir"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-ihr-nom",
    term: "ihr",
    translation: "vosotros/ustedes",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "ihr"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-plural-nom",
    term: "sie",
    translation: "ellos/ellas",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "sie (plural)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-formal-nom",
    term: "Sie",
    translation: "usted/ustedes",
    notes: "pronombre personal, nominativ",
    context: ["A1", "pronombre", "nominativ", "Sie (formal)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES PERSONALES - AKKUSATIV ==========
  {
    id: "de-pron-ich-akk",
    term: "mich",
    translation: "me/a mí",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "ich"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-du-akk",
    term: "dich",
    translation: "te/a ti",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "du"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-er-akk",
    term: "ihn",
    translation: "lo/a él",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "er"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-akk",
    term: "sie",
    translation: "la/a ella",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "sie"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-es-akk",
    term: "es",
    translation: "ello",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "es"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-wir-akk",
    term: "uns",
    translation: "nos",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "wir"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-ihr-akk",
    term: "euch",
    translation: "os/a ustedes",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "ihr"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-plural-akk",
    term: "sie",
    translation: "los/las",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "sie (plural)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-formal-akk",
    term: "Sie",
    translation: "a usted/ustedes",
    notes: "pronombre personal, akkusativ",
    context: ["A1", "pronombre", "akkusativ", "Sie (formal)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES PERSONALES - DATIV ==========
  {
    id: "de-pron-ich-dat",
    term: "mir",
    translation: "me/a mí",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "ich"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-du-dat",
    term: "dir",
    translation: "te/a ti",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "du"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-er-dat",
    term: "ihm",
    translation: "le/a él",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "er"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-dat",
    term: "ihr",
    translation: "le/a ella",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "sie"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-es-dat",
    term: "ihm",
    translation: "le/a ello",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "es"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-wir-dat",
    term: "uns",
    translation: "nos",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "wir"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-ihr-dat",
    term: "euch",
    translation: "os/a ustedes",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "ihr"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-plural-dat",
    term: "ihnen",
    translation: "les/a ellos",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "sie (plural)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-formal-dat",
    term: "Ihnen",
    translation: "a usted/ustedes",
    notes: "pronombre personal, dativ",
    context: ["A1", "pronombre", "dativ", "Sie (formal)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES PERSONALES - GENITIV ==========
  {
    id: "de-pron-ich-gen",
    term: "meiner",
    translation: "de mí",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "ich"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-du-gen",
    term: "deiner",
    translation: "de ti",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "du"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-er-gen",
    term: "seiner",
    translation: "de él",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "er"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-gen",
    term: "ihrer",
    translation: "de ella",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "sie"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-es-gen",
    term: "seiner",
    translation: "de ello",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "es"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-wir-gen",
    term: "unser",
    translation: "de nosotros",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "wir"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-ihr-gen",
    term: "euer",
    translation: "de vosotros/ustedes",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "ihr"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-plural-gen",
    term: "ihrer",
    translation: "de ellos/ellas",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "sie (plural)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-sie-formal-gen",
    term: "Ihrer",
    translation: "de usted/ustedes",
    notes: "pronombre personal, genitiv",
    context: ["A1", "pronombre", "genitiv", "Sie (formal)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES REFLEXIVOS - AKKUSATIV ==========
  {
    id: "de-pron-refl-ich-akk",
    term: "mich",
    translation: "me (a mí mismo)",
    notes: "pronombre reflexivo, akkusativ",
    context: ["A1", "pronombre", "reflexivo", "akkusativ", "ich"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-refl-du-akk",
    term: "dich",
    translation: "te (a ti mismo)",
    notes: "pronombre reflexivo, akkusativ",
    context: ["A1", "pronombre", "reflexivo", "akkusativ", "du"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-refl-sich-akk",
    term: "sich",
    translation: "se (a sí mismo)",
    notes: "pronombre reflexivo, akkusativ",
    context: ["A1", "pronombre", "reflexivo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-refl-wir-akk",
    term: "uns",
    translation: "nos (a nosotros mismos)",
    notes: "pronombre reflexivo, akkusativ",
    context: ["A1", "pronombre", "reflexivo", "akkusativ", "wir"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-refl-ihr-akk",
    term: "euch",
    translation: "os (a vosotros mismos)",
    notes: "pronombre reflexivo, akkusativ",
    context: ["A1", "pronombre", "reflexivo", "akkusativ", "ihr"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES REFLEXIVOS - DATIV ==========
  {
    id: "de-pron-refl-ich-dat",
    term: "mir",
    translation: "me (a mí mismo)",
    notes: "pronombre reflexivo, dativ",
    context: ["A1", "pronombre", "reflexivo", "dativ", "ich"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-refl-du-dat",
    term: "dir",
    translation: "te (a ti mismo)",
    notes: "pronombre reflexivo, dativ",
    context: ["A1", "pronombre", "reflexivo", "dativ", "du"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-refl-sich-dat",
    term: "sich",
    translation: "se (a sí mismo)",
    notes: "pronombre reflexivo, dativ",
    context: ["A1", "pronombre", "reflexivo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-refl-wir-dat",
    term: "uns",
    translation: "nos (a nosotros mismos)",
    notes: "pronombre reflexivo, dativ",
    context: ["A1", "pronombre", "reflexivo", "dativ", "wir"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-pron-refl-ihr-dat",
    term: "euch",
    translation: "os (a vosotros mismos)",
    notes: "pronombre reflexivo, dativ",
    context: ["A1", "pronombre", "reflexivo", "dativ", "ihr"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES POSESIVOS - MEIN ==========
  {
    id: "de-poss-mein-nom-m",
    term: "mein",
    translation: "mi",
    notes: "pronombre posesivo, nominativ masculino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-nom-f",
    term: "meine",
    translation: "mi",
    notes: "pronombre posesivo, nominativ femenino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-nom-n",
    term: "mein",
    translation: "mi",
    notes: "pronombre posesivo, nominativ neutro",
    context: ["A1", "pronombre", "posesivo", "nominativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-nom-pl",
    term: "meine",
    translation: "mis",
    notes: "pronombre posesivo, nominativ plural",
    context: ["A1", "pronombre", "posesivo", "nominativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-akk-m",
    term: "meinen",
    translation: "mi",
    notes: "pronombre posesivo, akkusativ masculino",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-akk-f",
    term: "meine",
    translation: "mi",
    notes: "pronombre posesivo, akkusativ femenino",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-akk-n",
    term: "mein",
    translation: "mi",
    notes: "pronombre posesivo, akkusativ neutro",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-akk-pl",
    term: "meine",
    translation: "mis",
    notes: "pronombre posesivo, akkusativ plural",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-dat-m",
    term: "meinem",
    translation: "mi",
    notes: "pronombre posesivo, dativ masculino",
    context: ["A1", "pronombre", "posesivo", "dativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-dat-f",
    term: "meiner",
    translation: "mi",
    notes: "pronombre posesivo, dativ femenino",
    context: ["A1", "pronombre", "posesivo", "dativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-dat-n",
    term: "meinem",
    translation: "mi",
    notes: "pronombre posesivo, dativ neutro",
    context: ["A1", "pronombre", "posesivo", "dativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-dat-pl",
    term: "meinen",
    translation: "mis",
    notes: "pronombre posesivo, dativ plural",
    context: ["A1", "pronombre", "posesivo", "dativ", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-gen-m",
    term: "meines",
    translation: "de mi",
    notes: "pronombre posesivo, genitiv masculino",
    context: ["A1", "pronombre", "posesivo", "genitiv", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-gen-f",
    term: "meiner",
    translation: "de mi",
    notes: "pronombre posesivo, genitiv femenino",
    context: ["A1", "pronombre", "posesivo", "genitiv", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-gen-n",
    term: "meines",
    translation: "de mi",
    notes: "pronombre posesivo, genitiv neutro",
    context: ["A1", "pronombre", "posesivo", "genitiv", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-mein-gen-pl",
    term: "meiner",
    translation: "de mis",
    notes: "pronombre posesivo, genitiv plural",
    context: ["A1", "pronombre", "posesivo", "genitiv", "mein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES POSESIVOS - DEIN ==========
  {
    id: "de-poss-dein-nom-m",
    term: "dein",
    translation: "tu",
    notes: "pronombre posesivo, nominativ masculino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "dein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-dein-nom-f",
    term: "deine",
    translation: "tu",
    notes: "pronombre posesivo, nominativ femenino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "dein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-dein-nom-n",
    term: "dein",
    translation: "tu",
    notes: "pronombre posesivo, nominativ neutro",
    context: ["A1", "pronombre", "posesivo", "nominativ", "dein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-dein-akk-m",
    term: "deinen",
    translation: "tu",
    notes: "pronombre posesivo, akkusativ masculino",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "dein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-dein-dat-m",
    term: "deinem",
    translation: "tu",
    notes: "pronombre posesivo, dativ masculino",
    context: ["A1", "pronombre", "posesivo", "dativ", "dein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-dein-gen-m",
    term: "deines",
    translation: "de tu",
    notes: "pronombre posesivo, genitiv masculino",
    context: ["A1", "pronombre", "posesivo", "genitiv", "dein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES POSESIVOS - SEIN (masculino/neutro) ==========
  {
    id: "de-poss-sein-nom-m",
    term: "sein",
    translation: "su (de él)",
    notes: "pronombre posesivo, nominativ masculino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "sein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-sein-nom-f",
    term: "seine",
    translation: "su (de él)",
    notes: "pronombre posesivo, nominativ femenino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "sein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-sein-akk-m",
    term: "seinen",
    translation: "su (de él)",
    notes: "pronombre posesivo, akkusativ masculino",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "sein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-sein-dat-m",
    term: "seinem",
    translation: "su (de él)",
    notes: "pronombre posesivo, dativ masculino",
    context: ["A1", "pronombre", "posesivo", "dativ", "sein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-sein-gen-m",
    term: "seines",
    translation: "de su (de él)",
    notes: "pronombre posesivo, genitiv masculino",
    context: ["A1", "pronombre", "posesivo", "genitiv", "sein"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES POSESIVOS - IHR (femenino) ==========
  {
    id: "de-poss-ihr-fem-nom-m",
    term: "ihr",
    translation: "su (de ella)",
    notes: "pronombre posesivo, nominativ masculino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "ihr (fem)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-ihr-fem-nom-f",
    term: "ihre",
    translation: "su (de ella)",
    notes: "pronombre posesivo, nominativ femenino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "ihr (fem)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-ihr-fem-akk-m",
    term: "ihren",
    translation: "su (de ella)",
    notes: "pronombre posesivo, akkusativ masculino",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "ihr (fem)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-ihr-fem-dat-m",
    term: "ihrem",
    translation: "su (de ella)",
    notes: "pronombre posesivo, dativ masculino",
    context: ["A1", "pronombre", "posesivo", "dativ", "ihr (fem)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-ihr-fem-gen-m",
    term: "ihres",
    translation: "de su (de ella)",
    notes: "pronombre posesivo, genitiv masculino",
    context: ["A1", "pronombre", "posesivo", "genitiv", "ihr (fem)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES POSESIVOS - UNSER ==========
  {
    id: "de-poss-unser-nom-m",
    term: "unser",
    translation: "nuestro",
    notes: "pronombre posesivo, nominativ masculino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "unser"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-unser-nom-f",
    term: "unsere",
    translation: "nuestra",
    notes: "pronombre posesivo, nominativ femenino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "unser"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-unser-akk-m",
    term: "unseren",
    translation: "nuestro",
    notes: "pronombre posesivo, akkusativ masculino",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "unser"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-unser-dat-m",
    term: "unserem",
    translation: "nuestro",
    notes: "pronombre posesivo, dativ masculino",
    context: ["A1", "pronombre", "posesivo", "dativ", "unser"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-unser-gen-m",
    term: "unseres",
    translation: "de nuestro",
    notes: "pronombre posesivo, genitiv masculino",
    context: ["A1", "pronombre", "posesivo", "genitiv", "unser"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES POSESIVOS - EUER ==========
  {
    id: "de-poss-euer-nom-m",
    term: "euer",
    translation: "vuestro",
    notes: "pronombre posesivo, nominativ masculino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "euer"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-euer-nom-f",
    term: "eure",
    translation: "vuestra",
    notes: "pronombre posesivo, nominativ femenino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "euer"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-euer-akk-m",
    term: "euren",
    translation: "vuestro",
    notes: "pronombre posesivo, akkusativ masculino",
    context: ["A1", "pronombre", "posesivo", "akkusativ", "euer"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-euer-dat-m",
    term: "eurem",
    translation: "vuestro",
    notes: "pronombre posesivo, dativ masculino",
    context: ["A1", "pronombre", "posesivo", "dativ", "euer"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-euer-gen-m",
    term: "eures",
    translation: "de vuestro",
    notes: "pronombre posesivo, genitiv masculino",
    context: ["A1", "pronombre", "posesivo", "genitiv", "euer"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES POSESIVOS - IHR (plural/formal) ==========
  {
    id: "de-poss-ihr-plural-nom-m",
    term: "ihr",
    translation: "su (de ellos)",
    notes: "pronombre posesivo, nominativ masculino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "ihr (plural)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-ihr-plural-nom-f",
    term: "ihre",
    translation: "su (de ellos)",
    notes: "pronombre posesivo, nominativ femenino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "ihr (plural)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-Ihr-formal-nom-m",
    term: "Ihr",
    translation: "su (de usted)",
    notes: "pronombre posesivo, nominativ masculino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "Ihr (formal)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-poss-Ihr-formal-nom-f",
    term: "Ihre",
    translation: "su (de usted)",
    notes: "pronombre posesivo, nominativ femenino",
    context: ["A1", "pronombre", "posesivo", "nominativ", "Ihr (formal)"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES DEMOSTRATIVOS - DIESER ==========
  {
    id: "de-demo-dieser-nom-m",
    term: "dieser",
    translation: "este",
    notes: "pronombre demostrativo, nominativ masculino",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-diese-nom-f",
    term: "diese",
    translation: "esta",
    notes: "pronombre demostrativo, nominativ femenino",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dieses-nom-n",
    term: "dieses",
    translation: "esto",
    notes: "pronombre demostrativo, nominativ neutro",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-diese-nom-pl",
    term: "diese",
    translation: "estos/estas",
    notes: "pronombre demostrativo, nominativ plural",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dieser-akk-m",
    term: "diesen",
    translation: "este",
    notes: "pronombre demostrativo, akkusativ masculino",
    context: ["A1", "pronombre", "demostrativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-diese-akk-f",
    term: "diese",
    translation: "esta",
    notes: "pronombre demostrativo, akkusativ femenino",
    context: ["A1", "pronombre", "demostrativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dieses-akk-n",
    term: "dieses",
    translation: "esto",
    notes: "pronombre demostrativo, akkusativ neutro",
    context: ["A1", "pronombre", "demostrativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-diesem-dat-m",
    term: "diesem",
    translation: "este",
    notes: "pronombre demostrativo, dativ masculino",
    context: ["A1", "pronombre", "demostrativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dieser-dat-f",
    term: "dieser",
    translation: "esta",
    notes: "pronombre demostrativo, dativ femenino",
    context: ["A1", "pronombre", "demostrativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-diesem-dat-n",
    term: "diesem",
    translation: "esto",
    notes: "pronombre demostrativo, dativ neutro",
    context: ["A1", "pronombre", "demostrativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dieses-gen-m",
    term: "dieses",
    translation: "de este",
    notes: "pronombre demostrativo, genitiv masculino",
    context: ["A1", "pronombre", "demostrativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dieser-gen-f",
    term: "dieser",
    translation: "de esta",
    notes: "pronombre demostrativo, genitiv femenino",
    context: ["A1", "pronombre", "demostrativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES DEMOSTRATIVOS - JENER ==========
  {
    id: "de-demo-jener-nom-m",
    term: "jener",
    translation: "aquel",
    notes: "pronombre demostrativo, nominativ masculino",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-jene-nom-f",
    term: "jene",
    translation: "aquella",
    notes: "pronombre demostrativo, nominativ femenino",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-jenes-nom-n",
    term: "jenes",
    translation: "aquello",
    notes: "pronombre demostrativo, nominativ neutro",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-jener-akk-m",
    term: "jenen",
    translation: "aquel",
    notes: "pronombre demostrativo, akkusativ masculino",
    context: ["A1", "pronombre", "demostrativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-jenem-dat-m",
    term: "jenem",
    translation: "aquel",
    notes: "pronombre demostrativo, dativ masculino",
    context: ["A1", "pronombre", "demostrativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-jenes-gen-m",
    term: "jenes",
    translation: "de aquel",
    notes: "pronombre demostrativo, genitiv masculino",
    context: ["A1", "pronombre", "demostrativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES DEMOSTRATIVOS/RELATIVOS - DER/DIE/DAS ==========
  {
    id: "de-demo-der-nom-m",
    term: "der",
    translation: "ese/el que",
    notes: "pronombre demostrativo/relativo, nominativ masculino",
    context: ["A1", "pronombre", "demostrativo", "relativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-die-nom-f",
    term: "die",
    translation: "esa/la que",
    notes: "pronombre demostrativo/relativo, nominativ femenino",
    context: ["A1", "pronombre", "demostrativo", "relativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-das-nom-n",
    term: "das",
    translation: "eso/lo que",
    notes: "pronombre demostrativo/relativo, nominativ neutro",
    context: ["A1", "pronombre", "demostrativo", "relativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-die-nom-pl",
    term: "die",
    translation: "esos/los que",
    notes: "pronombre demostrativo/relativo, nominativ plural",
    context: ["A1", "pronombre", "demostrativo", "relativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-der-akk-m",
    term: "den",
    translation: "ese/al que",
    notes: "pronombre demostrativo/relativo, akkusativ masculino",
    context: ["A1", "pronombre", "demostrativo", "relativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-die-akk-f",
    term: "die",
    translation: "esa/a la que",
    notes: "pronombre demostrativo/relativo, akkusativ femenino",
    context: ["A1", "pronombre", "demostrativo", "relativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-das-akk-n",
    term: "das",
    translation: "eso/lo que",
    notes: "pronombre demostrativo/relativo, akkusativ neutro",
    context: ["A1", "pronombre", "demostrativo", "relativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-der-dat-m",
    term: "dem",
    translation: "ese/al que",
    notes: "pronombre demostrativo/relativo, dativ masculino",
    context: ["A1", "pronombre", "demostrativo", "relativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-die-dat-f",
    term: "der",
    translation: "esa/a la que",
    notes: "pronombre demostrativo/relativo, dativ femenino",
    context: ["A1", "pronombre", "demostrativo", "relativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-das-dat-n",
    term: "dem",
    translation: "eso/a lo que",
    notes: "pronombre demostrativo/relativo, dativ neutro",
    context: ["A1", "pronombre", "demostrativo", "relativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-der-gen-m",
    term: "dessen",
    translation: "de ese/cuyo",
    notes: "pronombre demostrativo/relativo, genitiv masculino",
    context: ["A1", "pronombre", "demostrativo", "relativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-die-gen-f",
    term: "deren",
    translation: "de esa/cuya",
    notes: "pronombre demostrativo/relativo, genitiv femenino",
    context: ["A1", "pronombre", "demostrativo", "relativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-das-gen-n",
    term: "dessen",
    translation: "de eso/cuyo",
    notes: "pronombre demostrativo/relativo, genitiv neutro",
    context: ["A1", "pronombre", "demostrativo", "relativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES DEMOSTRATIVOS - DERJENIGE ==========
  {
    id: "de-demo-derjenige-nom-m",
    term: "derjenige",
    translation: "el que",
    notes: "pronombre demostrativo, nominativ masculino",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-diejenige-nom-f",
    term: "diejenige",
    translation: "la que",
    notes: "pronombre demostrativo, nominativ femenino",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dasjenige-nom-n",
    term: "dasjenige",
    translation: "lo que",
    notes: "pronombre demostrativo, nominativ neutro",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-derjenige-akk-m",
    term: "denjenigen",
    translation: "al que",
    notes: "pronombre demostrativo, akkusativ masculino",
    context: ["A1", "pronombre", "demostrativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-derjenige-dat-m",
    term: "demjenigen",
    translation: "al que",
    notes: "pronombre demostrativo, dativ masculino",
    context: ["A1", "pronombre", "demostrativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-derjenige-gen-m",
    term: "desjenigen",
    translation: "del que",
    notes: "pronombre demostrativo, genitiv masculino",
    context: ["A1", "pronombre", "demostrativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES DEMOSTRATIVOS - DERSELBE ==========
  {
    id: "de-demo-derselbe-nom-m",
    term: "derselbe",
    translation: "el mismo",
    notes: "pronombre demostrativo, nominativ masculino",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dieselbe-nom-f",
    term: "dieselbe",
    translation: "la misma",
    notes: "pronombre demostrativo, nominativ femenino",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-dasselbe-nom-n",
    term: "dasselbe",
    translation: "lo mismo",
    notes: "pronombre demostrativo, nominativ neutro",
    context: ["A1", "pronombre", "demostrativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-derselbe-akk-m",
    term: "denselben",
    translation: "al mismo",
    notes: "pronombre demostrativo, akkusativ masculino",
    context: ["A1", "pronombre", "demostrativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-derselbe-dat-m",
    term: "demselben",
    translation: "al mismo",
    notes: "pronombre demostrativo, dativ masculino",
    context: ["A1", "pronombre", "demostrativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-demo-derselbe-gen-m",
    term: "desselben",
    translation: "del mismo",
    notes: "pronombre demostrativo, genitiv masculino",
    context: ["A1", "pronombre", "demostrativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES RELATIVOS - WELCHER ==========
  {
    id: "de-rel-welcher-nom-m",
    term: "welcher",
    translation: "cual/que",
    notes: "pronombre relativo/interrogativo, nominativ masculino",
    context: ["A1", "pronombre", "relativo", "interrogativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-rel-welche-nom-f",
    term: "welche",
    translation: "cual/que",
    notes: "pronombre relativo/interrogativo, nominativ femenino",
    context: ["A1", "pronombre", "relativo", "interrogativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-rel-welches-nom-n",
    term: "welches",
    translation: "cual/que",
    notes: "pronombre relativo/interrogativo, nominativ neutro",
    context: ["A1", "pronombre", "relativo", "interrogativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-rel-welcher-akk-m",
    term: "welchen",
    translation: "cual/que",
    notes: "pronombre relativo/interrogativo, akkusativ masculino",
    context: ["A1", "pronombre", "relativo", "interrogativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-rel-welcher-dat-m",
    term: "welchem",
    translation: "cual/que",
    notes: "pronombre relativo/interrogativo, dativ masculino",
    context: ["A1", "pronombre", "relativo", "interrogativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-rel-welcher-gen-m",
    term: "welches",
    translation: "de cual/cuyo",
    notes: "pronombre relativo/interrogativo, genitiv masculino",
    context: ["A1", "pronombre", "relativo", "interrogativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES INTERROGATIVOS - WER ==========
  {
    id: "de-int-wer-nom",
    term: "wer",
    translation: "quién",
    notes: "pronombre interrogativo, nominativ",
    context: ["A1", "pronombre", "interrogativo", "nominativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-int-wer-akk",
    term: "wen",
    translation: "a quién",
    notes: "pronombre interrogativo, akkusativ",
    context: ["A1", "pronombre", "interrogativo", "akkusativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-int-wer-dat",
    term: "wem",
    translation: "a quién",
    notes: "pronombre interrogativo, dativ",
    context: ["A1", "pronombre", "interrogativo", "dativ"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-int-wer-gen",
    term: "wessen",
    translation: "de quién",
    notes: "pronombre interrogativo, genitiv",
    context: ["A1", "pronombre", "interrogativo", "genitiv"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES INTERROGATIVOS - WAS ==========
  {
    id: "de-int-was",
    term: "was",
    translation: "qué",
    notes: "pronombre interrogativo/relativo",
    context: ["A1", "pronombre", "interrogativo", "relativo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-int-was-fuer-ein",
    term: "was für ein",
    translation: "qué tipo de",
    notes: "pronombre interrogativo",
    context: ["A1", "pronombre", "interrogativo"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },

  // ========== PRONOMBRES INDEFINIDOS ==========
  {
    id: "de-indef-man",
    term: "man",
    translation: "uno/se",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-jemand",
    term: "jemand",
    translation: "alguien",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-niemand",
    term: "niemand",
    translation: "nadie",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-etwas",
    term: "etwas",
    translation: "algo",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-nichts",
    term: "nichts",
    translation: "nada",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-alle",
    term: "alle",
    translation: "todos",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-alles",
    term: "alles",
    translation: "todo",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-einige",
    term: "einige",
    translation: "algunos",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-etliche",
    term: "etliche",
    translation: "varios",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-manche",
    term: "manche",
    translation: "algunos",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-mehrere",
    term: "mehrere",
    translation: "varios",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-viele",
    term: "viele",
    translation: "muchos",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-wenige",
    term: "wenige",
    translation: "pocos",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-andere",
    term: "andere",
    translation: "otros",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-jeder",
    term: "jeder",
    translation: "cada",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-jede",
    term: "jede",
    translation: "cada",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-jedes",
    term: "jedes",
    translation: "cada",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-beide",
    term: "beide",
    translation: "ambos",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-einer",
    term: "einer",
    translation: "uno",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-eine",
    term: "eine",
    translation: "una",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-eines",
    term: "eines",
    translation: "uno",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-keiner",
    term: "keiner",
    translation: "ninguno",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-keine",
    term: "keine",
    translation: "ninguna",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-keines",
    term: "keines",
    translation: "ninguno",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-irgendein",
    term: "irgendein",
    translation: "alguno/cualquiera",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-irgendwer",
    term: "irgendwer",
    translation: "alguien",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
  {
    id: "de-indef-irgendetwas",
    term: "irgendetwas",
    translation: "algo",
    notes: "pronombre indefinido",
    context: ["A1", "pronombre", "indefinido"],
    contextForPractice: [],
    baseScore: 10,
    lastPracticedAt: null,
    createdAt: "2025-12-19T20:40:00.000Z",
  },
]

export default pronombres
